package model

import "encoding/xml"

type Configuration struct {
	Username string
	Password string
	Hostname string
	Database string
}

type Cfgmml struct {
	XMLName        xml.Name     `xml:"BACKUPCFG"`
	SchemaLocation string       `xml:"spec,attr"`
	SPECSYNCDATA   SpecSyncData `xml:"syndata"`
}

type SpecSyncData struct {
	XMLName xml.Name `xml:"syndata"`
	CLASSES []Class  `xml:"class"`
}

type Class struct {
	XMLName                   xml.Name                   `xml:"class"`
	ALMCURCFGS                []Almcurcfg                `xml:"ALMCURCFG"`
	ALMPORTS                  []Almport                  `xml:"ALMPORT"`
	ANRS                      []Anr                      `xml:"ANR"`
	ANRMEASUREPARAMS          []Anrmeasureparam          `xml:"ANRMeasureParam"`
	ANTENNAPORTS              []Antennaport              `xml:"ANTENNAPORT"`
	APPCERTS                  []Appcert                  `xml:"APPCERT"`
	APPLICATIONS              []Application              `xml:"APPLICATION"`
	ASPARAGROUPS              []Asparagroup              `xml:"AsParaGroup"`
	BASEBANDEQMS              []Basebandeqm              `xml:"BASEBANDEQM"`
	BBPS                      []Bbp                      `xml:"BBP"`
	BBUFANS                   []Bbufan                   `xml:"BBUFAN"`
	BCCHCFGS                  []Bcchcfg                  `xml:"BcchCfg"`
	BLINDNCELLOPTS            []Blindncellopt            `xml:"BlindNcellOpt"`
	BRDRESASSIGNMENTS         []Brdresassignment         `xml:"BRDRESASSIGNMENT"`
	CABINETS                  []Cabinet                  `xml:"CABINET"`
	CAGROUPS                  []Cagroup                  `xml:"CaGroup"`
	CAGROUPCELLS              []Cagroupcell              `xml:"CaGroupCell"`
	CAGROUPSCELLCFGS          []Cagroupscellcfg          `xml:"CaGroupSCellCfg"`
	CAMGTCFGS                 []Camgtcfg                 `xml:"CaMgtCfg"`
	CASCADEPORTS              []Cascadeport              `xml:"CASCADEPORT"`
	CELLS                     []Cell                     `xml:"Cell"`
	CELLACBARS                []Cellacbar                `xml:"CellAcBar"`
	CELLACCESSES              []Cellaccess               `xml:"CellAccess"`
	CELLALGOSWITCHES          []Cellalgoswitch           `xml:"CellAlgoSwitch"`
	CELLBACKOFFS              []Cellbackoff              `xml:"CellBackOff"`
	CELLBFS                   []Cellbf                   `xml:"CellBf"`
	CELLBFMIMOPARACFGS        []Cellbfmimoparacfg        `xml:"CellBfMimoParaCfg"`
	CELLCECFGS                []Cellcecfg                `xml:"CellCeCfg"`
	CELLCESCHCFGS             []Cellceschcfg             `xml:"CellCeSchCfg"`
	CELLCHPWRCFGS             []Cellchpwrcfg             `xml:"CellChPwrCfg"`
	CELLCOUNTERPARAGROUPS     []Cellcounterparagroup     `xml:"CellCounterParaGroup"`
	CELLCQIADAPTIVECFGS       []Cellcqiadaptivecfg       `xml:"CellCqiAdaptiveCfg"`
	CELLCQIADJALGOS           []Cellcqiadjalgo           `xml:"CellCqiAdjAlgo"`
	CELLCSIRSPARACFGS         []Cellcsirsparacfg         `xml:"CellCsiRsParaCfg"`
	CELLCSPCPARAS             []Cellcspcpara             `xml:"CellCspcPara"`
	CELLDACQCFGS              []Celldacqcfg              `xml:"CellDacqCfg"`
	CELLDLCOMPALGOS           []Celldlcompalgo           `xml:"CellDlCompAlgo"`
	CELLDLICICS               []Celldlicic               `xml:"CellDlIcic"`
	CELLDLPCPDCCHES           []Celldlpcpdcch            `xml:"CellDlpcPdcch"`
	CELLDLPCPDSCHES           []Celldlpcpdsch            `xml:"CellDlpcPdsch"`
	CELLDLPCPDSCHPAS          []Celldlpcpdschpa          `xml:"CellDlpcPdschPa"`
	CELLDLPCPHICHES           []Celldlpcphich            `xml:"CellDlpcPhich"`
	CELLDLSCHALGOS            []Celldlschalgo            `xml:"CellDlschAlgo"`
	CELLDRXPARAS              []Celldrxpara              `xml:"CellDrxPara"`
	CELLDRXSPECIALPARAS       []Celldrxspecialpara       `xml:"CellDrxSpecialPara"`
	CELLDSSES                 []Celldss                  `xml:"CellDss"`
	CELLDYNACBARALGOPARAS     []Celldynacbaralgopara     `xml:"CellDynAcBarAlgoPara"`
	CELLEABALGOPARAS          []Celleabalgopara          `xml:"CellEABAlgoPara"`
	CELLEICICS                []Celleicic                `xml:"CellEicic"`
	CELLEMTCALGOS             []Cellemtcalgo             `xml:"CellEmtcAlgo"`
	CELLHOPARACFGS            []Cellhoparacfg            `xml:"CellHoParaCfg"`
	CELLIDPRDUPTS             []Cellidprdupt             `xml:"CellIdPrdUpt"`
	CELLIICSPARAS             []Celliicspara             `xml:"CellIIcsPara"`
	CELLLOWPOWERS             []Celllowpower             `xml:"CellLowPower"`
	CELLLTEFLEXBWS            []Celllteflexbw            `xml:"CellLteFlexBw"`
	CELLLTEFLEXBWITFCFGS      []Celllteflexbwitfcfg      `xml:"CellLteFlexBwItfCfg"`
	CELLMBFCSES               []Cellmbfcs                `xml:"CellMbfcs"`
	CELLMBMSCFGS              []Cellmbmscfg              `xml:"CellMBMSCfg"`
	CELLMCPARAS               []Cellmcpara               `xml:"CellMcPara"`
	CELLMIMOPARACFGS          []Cellmimoparacfg          `xml:"CellMimoParaCfg"`
	CELLMLBS                  []Cellmlb                  `xml:"CellMLB"`
	CELLMLBAUTOGROUPS         []Cellmlbautogroup         `xml:"CellMlbAutoGroup"`
	CELLMLBHOS                []Cellmlbho                `xml:"CellMlbHo"`
	CELLMLBUESELS             []Cellmlbuesel             `xml:"CellMlbUeSel"`
	CELLMMALGOS               []Cellmmalgo               `xml:"CellMMAlgo"`
	CELLMROS                  []Cellmro                  `xml:"CellMro"`
	CELLNOACCESSALMPARAS      []Cellnoaccessalmpara      `xml:"CELLNOACCESSALMPARA"`
	CELLOPS                   []Cellop                   `xml:"CellOp"`
	CELLPCALGOS               []Cellpcalgo               `xml:"CellPcAlgo"`
	CELLPDCCHALGOS            []Cellpdcchalgo            `xml:"CellPdcchAlgo"`
	CELLPDCCHCECFGS           []Cellpdcchcecfg           `xml:"CellPdcchCECfg"`
	CELLPRBVALMLBS            []Cellprbvalmlb            `xml:"CellPrbValMlb"`
	CELLPUCCHALGOS            []Cellpucchalgo            `xml:"CellPucchAlgo"`
	CELLQCIPARAS              []Cellqcipara              `xml:"CellQciPara"`
	CELLRACHALGOS             []Cellrachalgo             `xml:"CellRachAlgo"`
	CELLRACHCECFGS            []Cellrachcecfg            `xml:"CellRachCECfg"`
	CELLRACTHDS               []Cellracthd               `xml:"CellRacThd"`
	CELLRESELS                []Cellresel                `xml:"CellResel"`
	CELLRESELGERANS           []Cellreselgeran           `xml:"CellReselGeran"`
	CELLRESELUTRANS           []Cellreselutran           `xml:"CellReselUtran"`
	CELLRFSHUTDOWNS           []Cellrfshutdown           `xml:"CellRfShutdown"`
	CELLRICALGOS              []Cellricalgo              `xml:"CellRicAlgo"`
	CELLSELS                  []Cellsel                  `xml:"CellSel"`
	CELLSERVICEDIFFCFGS       []Cellservicediffcfg       `xml:"CellServiceDiffCfg"`
	CELLSHUTDOWNS             []Cellshutdown             `xml:"CellShutdown"`
	CELLSIMAPS                []Cellsimap                `xml:"CellSiMap"`
	CELLSRLTES                []Cellsrlte                `xml:"CellSrlte"`
	CELLSRSADAPTIVECFGS       []Cellsrsadaptivecfg       `xml:"CellSrsAdaptiveCfg"`
	CELLSTANDARDQCIS          []Cellstandardqci          `xml:"CELLSTANDARDQCI"`
	CELLTTIBUNDLINGALGOS      []Cellttibundlingalgo      `xml:"CellTtiBundlingAlgo"`
	CELLUCIONPUSCHPARAS       []Cellucionpuschpara       `xml:"CellUciOnPuschPara"`
	CELLUEMEASCONTROLCFGS     []Celluemeascontrolcfg     `xml:"CellUeMeasControlCfg"`
	CELLULCOMPALGOS           []Cellulcompalgo           `xml:"CellUlCompAlgo"`
	CELLULICALGOS             []Cellulicalgo             `xml:"CellUlIcAlgo"`
	CELLULICICS               []Cellulicic               `xml:"CellUlIcic"`
	CELLULICICMCPARAS         []Cellulicicmcpara         `xml:"CellULIcicMcPara"`
	CELLULMIMOPARACFGS        []Cellulmimoparacfg        `xml:"CellUlMimoParaCfg"`
	CELLULPCCOMMS             []Cellulpccomm             `xml:"CellUlpcComm"`
	CELLULPCDEDICS            []Cellulpcdedic            `xml:"CellUlpcDedic"`
	CELLULSCHALGOS            []Cellulschalgo            `xml:"CellUlschAlgo"`
	CELLULUNIFIEDOLCS         []Cellulunifiedolc         `xml:"CellULUnifiedOLC"`
	CELLUSPARACFGS            []Cellusparacfg            `xml:"CellUSParaCfg"`
	CELLVMSES                 []Cellvms                  `xml:"CellVMS"`
	CELLWTTXPARACFGS          []Cellwttxparacfg          `xml:"CellWttxParaCfg"`
	CEPUCCHCFGS               []Cepucchcfg               `xml:"CePucchCfg"`
	CERACHCFGS                []Cerachcfg                `xml:"CeRachCfg"`
	CERTCFGS                  []Certcfg                  `xml:"CERTCFG"`
	CERTCHKTSKS               []Certchktsk               `xml:"CERTCHKTSK"`
	CERTDEPLOIES              []Certdeploy               `xml:"CERTDEPLOY"`
	CERTMKS                   []Certmk                   `xml:"CERTMK"`
	CERTREQS                  []Certreq                  `xml:"CERTREQ"`
	CHKS                      []Chk                      `xml:"CHK"`
	CLKDETECTS                []Clkdetect                `xml:"ClkDetect"`
	CLZEROBUFFERZONES         []Clzerobufferzone         `xml:"CLZeroBufferzone"`
	CNOPERATORS               []Cnoperator               `xml:"CnOperator"`
	CNOPERATORHOCFGS          []Cnoperatorhocfg          `xml:"CnOperatorHoCfg"`
	CNOPERATORQCIPARAS        []Cnoperatorqcipara        `xml:"CnOperatorQciPara"`
	CNOPERATORSTANDARDQCIS    []Cnoperatorstandardqci    `xml:"CNOPERATORSTANDARDQCI"`
	CNOPERATORTAS             []Cnoperatorta             `xml:"CnOperatorTa"`
	COUNTERCHECKPARAS         []Countercheckpara         `xml:"CounterCheckPara"`
	CPBEARERS                 []Cpbearer                 `xml:"CPBEARER"`
	CPRIPORTS                 []Cpriport                 `xml:"CPRIPORT"`
	CPSWITCHES                []Cpswitch                 `xml:"CPSWITCH"`
	CQIADAPTIVECFGS           []Cqiadaptivecfg           `xml:"CqiAdaptiveCfg"`
	CRLPOLICIES               []Crlpolicy                `xml:"CRLPOLICY"`
	CSFALLBACKBLINDHOCFGS     []Csfallbackblindhocfg     `xml:"CSFallBackBlindHoCfg"`
	CSFALLBACKHOS             []Csfallbackho             `xml:"CSFallBackHo"`
	CSFALLBACKPOLICYCFGS      []Csfallbackpolicycfg      `xml:"CSFallBackPolicyCfg"`
	CSPCALGOPARAS             []Cspcalgopara             `xml:"CspcAlgoPara"`
	DEVIPS                    []Devip                    `xml:"DEVIP"`
	DHCPRELAYSWITCHES         []Dhcprelayswitch          `xml:"DHCPRELAYSWITCH"`
	DHCPSVRIPS                []Dhcpsvrip                `xml:"DHCPSVRIP"`
	DHCPSWS                   []Dhcpsw                   `xml:"DHCPSW"`
	DIFPRIS                   []Difpri                   `xml:"DIFPRI"`
	DISTBASEDHOS              []Distbasedho              `xml:"DistBasedHO"`
	DLFLOWCTRLPARAS           []Dlflowctrlpara           `xml:"DLFLOWCTRLPARA"`
	DRXES                     []Drx                      `xml:"Drx"`
	DRXPARAGROUPS             []Drxparagroup             `xml:"DrxParaGroup"`
	DSCPMAPS                  []Dscpmap                  `xml:"DSCPMAP"`
	E1T1S                     []E1t1                     `xml:"E1T1"`
	E1T1BEARS                 []E1t1bear                 `xml:"E1T1BEAR"`
	E1T1BERS                  []E1t1ber                  `xml:"E1T1BER"`
	EMCS                      []Emc                      `xml:"Emc"`
	EMUS                      []Emu                      `xml:"EMU"`
	ENBCELLOPRSVDPARAS        []Enbcelloprsvdpara        `xml:"eNBCellOpRsvdPara"`
	ENBCELLQCIRSVDPARAS       []Enbcellqcirsvdpara       `xml:"eNBCellQciRsvdPara"`
	ENBCELLRSVDPARAS          []Enbcellrsvdpara          `xml:"eNBCellRsvdPara"`
	ENBCNOPQCIRSVDPARAS       []Enbcnopqcirsvdpara       `xml:"eNBCnOpQciRsvdPara"`
	ENBCNOPRSVDPARAS          []Enbcnoprsvdpara          `xml:"eNBCnOpRsvdPara"`
	ENBLICENSEALMTHDS         []Enblicensealmthd         `xml:"eNBLicenseAlmThd"`
	ENBQCIRSVDPARAS           []Enbqcirsvdpara           `xml:"eNBQciRsvdPara"`
	ENBRSVDPARAS              []Enbrsvdpara              `xml:"eNBRsvdPara"`
	ENERGYCONS                []Energycon                `xml:"ENERGYCON"`
	ENODEBALGOSWITCHES        []Enodebalgoswitch         `xml:"ENodeBAlgoSwitch"`
	ENODEBALMCFGS             []Enodebalmcfg             `xml:"eNodeBAlmCfg"`
	ENODEBAUTOPOWEROFFS       []Enodebautopoweroff       `xml:"eNodeBAutoPowerOff"`
	ENODEBCHROUTPUTCTRLS      []Enodebchroutputctrl      `xml:"eNodeBChrOutputCtrl"`
	ENODEBCIPHERCAPS          []Enodebciphercap          `xml:"ENodeBCipherCap"`
	ENODEBCONNSTATETIMERS     []Enodebconnstatetimer     `xml:"ENodeBConnStateTimer"`
	ENODEBFDDBBRESES          []Enodebfddbbres           `xml:"eNodeBFddBbRes"`
	ENODEBFLOWCTRLPARAS       []Enodebflowctrlpara       `xml:"eNodeBFlowCtrlPara"`
	ENODEBFRAMEOFFSETS        []Enodebframeoffset        `xml:"ENodeBFrameOffset"`
	ENODEBFUNCTIONS           []Enodebfunction           `xml:"eNodeBFunction"`
	ENODEBINTEGRITYCAPS       []Enodebintegritycap       `xml:"ENodeBIntegrityCap"`
	ENODEBMLBS                []Enodebmlb                `xml:"eNodeBMlb"`
	ENODEBNBPARAS             []Enodebnbpara             `xml:"ENodeBNbPara"`
	ENODEBRESMODEALGOS        []Enodebresmodealgo        `xml:"eNodeBResModeAlgo"`
	ENODEBSHARINGMODES        []Enodebsharingmode        `xml:"ENodeBSharingMode"`
	ENODEBSONDBCFGS           []Enodebsondbcfg           `xml:"eNodeBSonDBCfg"`
	ENODEBTDDBBRESES          []Enodebtddbbres           `xml:"eNodeBTddBbRes"`
	ENODEBTGALGCFGS           []Enodebtgalgcfg           `xml:"eNodeBTGAlgCfg"`
	ENODEBUSPARACFGS          []Enodebusparacfg          `xml:"eNodeBUSParaCfg"`
	EPGROUPS                  []Epgroup                  `xml:"EPGROUP"`
	EQUIPMENTS                []Equipment                `xml:"EQUIPMENT"`
	ETHPORTS                  []Ethport                  `xml:"ETHPORT"`
	EUCELLALMCFGS             []Eucellalmcfg             `xml:"EuCellAlmCfg"`
	EUCELLSECTOREQMS          []Eucellsectoreqm          `xml:"eUCellSectorEqm"`
	EUCOMMCELLSECTOREQMS      []Eucommcellsectoreqm      `xml:"eUCommCellSectorEqm"`
	EUCOSCHCFGS               []Eucoschcfg               `xml:"EuCoSchCfg"`
	EUCOSCHDLCOMPCFGS         []Eucoschdlcompcfg         `xml:"EuCoSchDLCoMPCfg"`
	EUCOSCHULICSCFGS          []Eucoschulicscfg          `xml:"EuCoSchULICSCfg"`
	EUEPCSECS                 []Euepcsec                 `xml:"EUEPCSec"`
	EUTRANEXTERNALCELLS       []Eutranexternalcell       `xml:"EutranExternalCell"`
	EUTRANINTERFREQNCELLS     []Eutraninterfreqncell     `xml:"EutranInterFreqNCell"`
	EUTRANINTERNFREQS         []Eutraninternfreq         `xml:"EutranInterNFreq"`
	EUTRANINTRAFREQNCELLS     []Eutranintrafreqncell     `xml:"EutranIntraFreqNCell"`
	EUULCOSCHCFGS             []Euulcoschcfg             `xml:"EuUlCoSchCfg"`
	EXTENDEDQCIS              []Extendedqci              `xml:"EXTENDEDQCI"`
	FDDRESMODES               []Fddresmode               `xml:"FddResMode"`
	FLTCORRENABLECFGS         []Fltcorrenablecfg         `xml:"FLTCORRENABLECFG"`
	FMUS                      []Fmu                      `xml:"FMU"`
	FTPCLTS                   []Ftpclt                   `xml:"FTPCLT"`
	FTPCLTPORTS               []Ftpcltport               `xml:"FTPCLTPORT"`
	GBTSABISCPS               []Gbtsabiscp               `xml:"GBTSABISCP"`
	GBTSBBRESES               []Gbtsbbres                `xml:"GBTSBBRES"`
	GBTSENERGYMGTPARAS        []Gbtsenergymgtpara        `xml:"GBTSENERGYMGTPARA"`
	GBTSFUNCTIONS             []Gbtsfunction             `xml:"GBTSFUNCTION"`
	GBTSGLOBALPARAS           []Gbtsglobalpara           `xml:"GBTSGLOBALPARA"`
	GBTSPATHES                []Gbtspath                 `xml:"GBTSPATH"`
	GERANEXTERNALCELLS        []Geranexternalcell        `xml:"GeranExternalCell"`
	GERANINTERFCFGS           []Geraninterfcfg           `xml:"GeranInterfCfg"`
	GERANNCELLS               []Geranncell               `xml:"GeranNcell"`
	GERANNFREQGROUPS          []Gerannfreqgroup          `xml:"GeranNfreqGroup"`
	GERANNFREQGROUPARFCNS     []Gerannfreqgrouparfcn     `xml:"GeranNfreqGroupArfcn"`
	GLOBALPROCSWITCHES        []Globalprocswitch         `xml:"GlobalProcSwitch"`
	GLOCELLS                  []Glocell                  `xml:"GLOCELL"`
	GLOCELLALGPARAS           []Glocellalgpara           `xml:"GLOCELLALGPARA"`
	GLOCELLENERGYMGTPARAS     []Glocellenergymgtpara     `xml:"GLOCELLENERGYMGTPARA"`
	GLOCELLOTHPARAS           []Glocellothpara           `xml:"GLOCELLOTHPARA"`
	GLOCELLRLALMPARAS         []Glocellrlalmpara         `xml:"GLOCELLRLALMPARA"`
	GLOCELLRSVDPARAS          []Glocellrsvdpara          `xml:"GLOCELLRSVDPARA"`
	GPSES                     []Gps                      `xml:"GPS"`
	GTPUS                     []Gtpu                     `xml:"GTPU"`
	GTRANSPARAS               []Gtranspara               `xml:"GTRANSPARA"`
	GTRANSPARAGWS             []Gtransparagw             `xml:"GTRANSPARAGW"`
	GTRXGROUPS                []Gtrxgroup                `xml:"GTRXGROUP"`
	GTRXGROUPSECTOREQMS       []Gtrxgroupsectoreqm       `xml:"GTRXGROUPSECTOREQM"`
	HIGHSPDADAPTIONPARAS      []Highspdadaptionpara      `xml:"HighSpdAdaptionPara"`
	HOMEASCOMMS               []Homeascomm               `xml:"HoMeasComm"`
	HTCDPAS                   []Htcdpa                   `xml:"HTCDPA"`
	IKECFGS                   []Ikecfg                   `xml:"IKECFG"`
	IMAGRPS                   []Imagrp                   `xml:"IMAGRP"`
	IMALNKS                   []Imalnk                   `xml:"IMALNK"`
	INGCHKTSKS                []Ingchktsk                `xml:"INGCHKTSK"`
	INTERFREQHOGROUPS         []Interfreqhogroup         `xml:"InterFreqHoGroup"`
	INTERRATCELLSHUTDOWNS     []Interratcellshutdown     `xml:"InterRatCellShutdown"`
	INTERRATHOCDMA1XRTTGROUPS []Interrathocdma1xrttgroup `xml:"InterRatHoCdma1xRttGroup"`
	INTERRATHOCDMAHRPDGROUPS  []Interrathocdmahrpdgroup  `xml:"InterRatHoCdmaHrpdGroup"`
	INTERRATHOCOMMS           []Interrathocomm           `xml:"InterRatHoComm"`
	INTERRATHOCOMMGROUPS      []Interrathocommgroup      `xml:"InterRatHoCommGroup"`
	INTERRATHOGERANGROUPS     []Interrathogerangroup     `xml:"InterRatHoGeranGroup"`
	INTERRATHOUTRANGROUPS     []Interrathoutrangroup     `xml:"InterRatHoUtranGroup"`
	INTERRATPOLICYCFGGROUPS   []Interratpolicycfggroup   `xml:"InterRatPolicyCfgGroup"`
	INTRAFREQHOGROUPS         []Intrafreqhogroup         `xml:"IntraFreqHoGroup"`
	INTRARATHOCOMMS           []Intrarathocomm           `xml:"IntraRatHoComm"`
	IOPSCFGS                  []Iopscfg                  `xml:"IopsCfg"`
	IPCLKLNKS                 []Ipclklnk                 `xml:"IPCLKLNK"`
	IPGUARDS                  []Ipguard                  `xml:"IPGUARD"`
	IPPATHES                  []Ippath                   `xml:"IPPATH"`
	IPPMSESSIONS              []Ippmsession              `xml:"IPPMSESSION"`
	IPRTS                     []Iprt                     `xml:"IPRT"`
	IRATNCELLCLASSMGTS        []Iratncellclassmgt        `xml:"IRATNCellClassMgt"`
	IUBS                      []Iub                      `xml:"IUB"`
	IUBCPS                    []Iubcp                    `xml:"IUBCP"`
	LANSWS                    []Lansw                    `xml:"LANSW"`
	LANSWITCHPORTS            []Lanswitchport            `xml:"LANSWITCHPORT"`
	LICENSECONTROLSTRATEGIES  []Licensecontrolstrategy   `xml:"LicenseControlStrategy"`
	LICRATIOS                 []Licratio                 `xml:"LicRatio"`
	LINECLKS                  []Lineclk                  `xml:"LINECLK"`
	LIOPTATOMRULES            []Lioptatomrule            `xml:"LIOptAtomRule"`
	LIOPTFEATURES             []Lioptfeature             `xml:"LIOptFeature"`
	LIOPTFUNCTIONS            []Lioptfunction            `xml:"LIOptFunction"`
	LIOPTRULES                []Lioptrule                `xml:"LIOptRule"`
	LIOPTRULEMEMBERS          []Lioptrulemember          `xml:"LIOptRuleMember"`
	LLDPGLOBALS               []Lldpglobal               `xml:"LLDPGLOBAL"`
	LOCALETHPORTS             []Localethport             `xml:"LOCALETHPORT"`
	LOCALIPS                  []Localip                  `xml:"LOCALIP"`
	LOCALIP6S                 []Localip6                 `xml:"LOCALIP6"`
	LOCALWAPS                 []Localwap                 `xml:"LOCALWAP"`
	LOCATIONS                 []Location                 `xml:"LOCATION"`
	LWAMGTCFGS                []Lwamgtcfg                `xml:"LwaMgtCfg"`
	MAINSALARMBINDS           []Mainsalarmbind           `xml:"MAINSALARMBIND"`
	MANRESALMRPTS             []Manresalmrpt             `xml:"MANRESALMRPT"`
	MBMSPARAS                 []Mbmspara                 `xml:"MBMSPara"`
	MMEFEATURECFGS            []Mmefeaturecfg            `xml:"MmeFeatureCfg"`
	MPTS                      []Mpt                      `xml:"MPT"`
	MPTRESASSIGNMENTS         []Mptresassignment         `xml:"MptResAssignment"`
	MROS                      []Mro                      `xml:"MRO"`
	NBCELLDLSCHCEALGOS        []Nbcelldlschcealgo        `xml:"NbCellDlSchCEAlgo"`
	NBCELLULSCHCEALGOS        []Nbcellulschcealgo        `xml:"NbCellUlSchCEAlgo"`
	NCELLCLASSMGTS            []Ncellclassmgt            `xml:"NCellClassMgt"`
	NCELLDLRSRPMEASPARAS      []Ncelldlrsrpmeaspara      `xml:"NCellDlRsrpMeasPara"`
	NCELLPARACFGS             []Ncellparacfg             `xml:"NCellParaCfg"`
	NCELLSRSMEASPARAS         []Ncellsrsmeaspara         `xml:"NCellSrsMeasPara"`
	NES                       []Ne                       `xml:"NE"`
	NEMNTS                    []Nemnt                    `xml:"NEMNT"`
	NODES                     []Node                     `xml:"NODE"`
	NODEBALGPARAS             []Nodebalgpara             `xml:"NODEBALGPARA"`
	NODEBBBRESES              []Nodebbbres               `xml:"NODEBBBRES"`
	NODEBCHRLEVELS            []Nodebchrlevel            `xml:"NODEBCHRLEVEL"`
	NODEBCLSPATIMERS          []Nodebclspatimer          `xml:"NODEBCLSPATIMER"`
	NODEBFUNCTIONS            []Nodebfunction            `xml:"NODEBFUNCTION"`
	NODEBLICENSEALMTHDS       []Nodeblicensealmthd       `xml:"NODEBLICENSEALMTHD"`
	NODEBMULTICELLGRPS        []Nodebmulticellgrp        `xml:"NODEBMULTICELLGRP"`
	NODEBOPTDYNADJPARAS       []Nodeboptdynadjpara       `xml:"NODEBOPTDYNADJPARA"`
	NODEBPOWEROUTAGES         []Nodebpoweroutage         `xml:"NODEBPOWEROUTAGE"`
	NODEBRESALLOCRULES        []Nodebresallocrule        `xml:"NODEBRESALLOCRULE"`
	NODEBRSVDPARAS            []Nodebrsvdpara            `xml:"NODEBRSVDPARA"`
	NODEBRULEACTIONPARAS      []Nodebruleactionpara      `xml:"NODEBRULEACTIONPARA"`
	NODEBSMTHPWRS             []Nodebsmthpwr             `xml:"NODEBSMTHPWR"`
	NODEBTRFOVERLOADTHDS      []Nodebtrfoverloadthd      `xml:"NODEBTRFOVERLOADTHD"`
	NODEBUEQOSENHANCES        []Nodebueqosenhance        `xml:"NODEBUEQOSENHANCE"`
	NTPCPS                    []Ntpcp                    `xml:"NTPCP"`
	OMCHES                    []Omch                     `xml:"OMCH"`
	OPS                       []Op                       `xml:"OP"`
	OUTPORTS                  []Outport                  `xml:"OUTPORT"`
	PARAAUTOOPTCFGS           []Paraautooptcfg           `xml:"ParaAutoOptCfg"`
	PCCFREQCFGS               []Pccfreqcfg               `xml:"PccFreqCfg"`
	PCCHCFGS                  []Pcchcfg                  `xml:"PCCHCfg"`
	PDCPROHCPARAS             []Pdcprohcpara             `xml:"PdcpRohcPara"`
	PDSCHCFGS                 []Pdschcfg                 `xml:"PDSCHCfg"`
	PEERCLKS                  []Peerclk                  `xml:"PEERCLK"`
	PEUS                      []Peu                      `xml:"PEU"`
	PHICHCFGS                 []Phichcfg                 `xml:"PHICHCfg"`
	PHYPORTS                  []Phyport                  `xml:"PHYPORT"`
	PLRTHRESHOLDS             []Plrthreshold             `xml:"PLRTHRESHOLD"`
	PMTUCFGS                  []Pmtucfg                  `xml:"PMTUCFG"`
	PORTPOLICIES              []Portpolicy               `xml:"PORTPOLICY"`
	PRI2QUES                  []Pri2que                  `xml:"PRI2QUE"`
	PRIVATECABANDCOMBS        []Privatecabandcomb        `xml:"PrivateCaBandComb"`
	PSUISES                   []Psuis                    `xml:"PSUIS"`
	PUCCHCFGS                 []Pucchcfg                 `xml:"PUCCHCfg"`
	PUSCHCFGS                 []Puschcfg                 `xml:"PUSCHCfg"`
	PUSCHPARAMS               []Puschparam               `xml:"PUSCHPARAM"`
	PWDPOLICIES               []Pwdpolicy                `xml:"PWDPOLICY"`
	QCIPARAS                  []Qcipara                  `xml:"QciPara"`
	QOEHOCOMMONCFGS           []Qoehocommoncfg           `xml:"QoEHoCommonCfg"`
	RACHCFGS                  []Rachcfg                  `xml:"RACHCfg"`
	RETS                      []Ret                      `xml:"RET"`
	RETDEVICEDATAS            []Retdevicedata            `xml:"RETDEVICEDATA"`
	RETPORTS                  []Retport                  `xml:"RETPORT"`
	RETSUBUNITS               []Retsubunit               `xml:"RETSUBUNIT"`
	RFUS                      []Rfu                      `xml:"RFU"`
	RLCPDCPPARAGROUPS         []Rlcpdcpparagroup         `xml:"RlcPdcpParaGroup"`
	RRCCONNSTATETIMERS        []Rrcconnstatetimer        `xml:"RrcConnStateTimer"`
	RRUS                      []Rru                      `xml:"RRU"`
	RRUCHAINS                 []Rruchain                 `xml:"RRUCHAIN"`
	RRUJOINTCALPARACFGS       []Rrujointcalparacfg       `xml:"RruJointCalParaCfg"`
	RSCGRPS                   []Rscgrp                   `xml:"RSCGRP"`
	RSCGRPALGS                []Rscgrpalg                `xml:"RSCGRPALG"`
	RXBRANCHES                []Rxbranch                 `xml:"RXBRANCH"`
	S1S                       []S1                       `xml:"S1"`
	S1INTERFACES              []S1interface              `xml:"S1Interface"`
	S1REESTTIMERS             []S1reesttimer             `xml:"S1ReestTimer"`
	SAALLNKS                  []Saallnk                  `xml:"SAALLNK"`
	SCAPPPARACFGS             []Scappparacfg             `xml:"ScAppParaCfg"`
	SCCFREQCFGS               []Sccfreqcfg               `xml:"SccFreqCfg"`
	SCPOLICIES                []Scpolicy                 `xml:"ScPolicy"`
	SCSERVICEQOSES            []Scserviceqos             `xml:"ScServiceQos"`
	SCTPHOSTS                 []Sctphost                 `xml:"SCTPHOST"`
	SCTPLNKS                  []Sctplnk                  `xml:"SCTPLNK"`
	SCTPPEERS                 []Sctppeer                 `xml:"SCTPPEER"`
	SCTPTEMPLATES             []Sctptemplate             `xml:"SCTPTEMPLATE"`
	SECTORS                   []Sector                   `xml:"SECTOR"`
	SECTOREQMS                []Sectoreqm                `xml:"SECTOREQM"`
	SERVICEDIFFSETTINGS       []Servicediffsetting       `xml:"ServiceDiffSetting"`
	SERVICEIDENTIFYPARAS      []Serviceidentifypara      `xml:"ServiceIdentifyPara"`
	SERVICEIFDLEARFCNGRPS     []Serviceifdlearfcngrp     `xml:"ServiceIfDlEarfcnGrp"`
	SERVICEIFHOCFGGROUPS      []Serviceifhocfggroup      `xml:"ServiceIfHoCfgGroup"`
	SERVICEIRHOCFGGROUPS      []Serviceirhocfggroup      `xml:"ServiceIrHoCfgGroup"`
	SFPS                      []Sfp                      `xml:"SFP"`
	SIMULOADS                 []Simuload                 `xml:"SimuLoad"`
	SINGLEIPSWITCHES          []Singleipswitch           `xml:"SINGLEIPSWITCH"`
	SRBCFGS                   []Srbcfg                   `xml:"SrbCfg"`
	SRBRLCPDCPCFGS            []Srbrlcpdcpcfg            `xml:"SrbRlcPdcpCfg"`
	SRCIPRTS                  []Srciprt                  `xml:"SRCIPRT"`
	SRSADAPTIVECFGS           []Srsadaptivecfg           `xml:"SRSADAPTIVECFG"`
	SRSCFGS                   []Srscfg                   `xml:"SRSCfg"`
	SSLS                      []Ssl                      `xml:"SSL"`
	STANDARDQCIS              []Standardqci              `xml:"STANDARDQCI"`
	SUBRACKS                  []Subrack                  `xml:"SUBRACK"`
	SYNCETHES                 []Synceth                  `xml:"SYNCETH"`
	TACALGS                   []Tacalg                   `xml:"TACALG"`
	TASMS                     []Tasm                     `xml:"TASM"`
	TBDSPINFOS                []Tbdspinfo                `xml:"TBDSPINFO"`
	TBLANGNOS                 []Tblangno                 `xml:"TBLANGNO"`
	TCPACKCTRLALGOS           []Tcpackctrlalgo           `xml:"TcpAckCtrlAlgo"`
	TCPACKLIMITALGS           []Tcpacklimitalg           `xml:"TCPACKLIMITALG"`
	TCPMSSCTRLS               []Tcpmssctrl               `xml:"TcpMssCtrl"`
	TCUS                      []Tcu                      `xml:"TCU"`
	TDDFRAMEOFFSETS           []Tddframeoffset           `xml:"TddFrameOffset"`
	TDDRESMODESWITCHES        []Tddresmodeswitch         `xml:"TddResModeSwitch"`
	TIMEALIGNMENTTIMERS       []Timealignmenttimer       `xml:"TimeAlignmentTimer"`
	TIMESRCS                  []Timesrc                  `xml:"TIMESRC"`
	TIMETHRDS                 []Timethrd                 `xml:"TIMETHRD"`
	TLDRALGS                  []Tldralg                  `xml:"TLDRALG"`
	TLFRSWITCHES              []Tlfrswitch               `xml:"TLFRSWITCH"`
	TOLCALGS                  []Tolcalg                  `xml:"TOLCALG"`
	TPEALGOS                  []Tpealgo                  `xml:"TpeAlgo"`
	TRPS                      []Trp                      `xml:"TRP"`
	TRUSTCERTS                []Trustcert                `xml:"TRUSTCERT"`
	TWAMPRESPONDERS           []Twampresponder           `xml:"TWAMPRESPONDER"`
	TXBRANCHES                []Txbranch                 `xml:"TXBRANCH"`
	TYPDRBBSRS                []Typdrbbsr                `xml:"TypDrbBsr"`
	TZS                       []Tz                       `xml:"TZ"`
	UDPPINGS                  []Udpping                  `xml:"UDPPING"`
	UDTS                      []Udt                      `xml:"UDT"`
	UDTPARAGRPS               []Udtparagrp               `xml:"UDTPARAGRP"`
	UECOOPERATIONPARAS        []Uecooperationpara        `xml:"UeCooperationPara"`
	UEIUS                     []Ueiu                     `xml:"UEIU"`
	UESPECDRXPARAGROUPS       []Uespecdrxparagroup       `xml:"UeSpecDrxParaGroup"`
	UETIMERCONSTS             []Uetimerconst             `xml:"UeTimerConst"`
	ULCSALGOPARAS             []Ulcsalgopara             `xml:"UlCsAlgoPara"`
	ULINTERFSUPPRESSCFGS      []Ulinterfsuppresscfg      `xml:"UlInterfSuppressCfg"`
	ULOCELLS                  []Ulocell                  `xml:"ULOCELL"`
	ULOCELLALGPARAS           []Ulocellalgpara           `xml:"ULOCELLALGPARA"`
	ULOCELLMACEPARAS          []Ulocellmacepara          `xml:"ULOCELLMACEPARA"`
	ULOCELLMACHSPARAS         []Ulocellmachspara         `xml:"ULOCELLMACHSPARA"`
	ULOCELLNOACCESSPARAS      []Ulocellnoaccesspara      `xml:"ULOCELLNOACCESSPARA"`
	ULOCELLR99ALGPARAS        []Ulocellr99algpara        `xml:"ULOCELLR99ALGPARA"`
	ULOCELLRSCLMTPARAS        []Ulocellrsclmtpara        `xml:"ULOCELLRSCLMTPARA"`
	ULOCELLRSVDPARAS          []Ulocellrsvdpara          `xml:"ULOCELLRSVDPARA"`
	ULOCELLSECTOREQMS         []Ulocellsectoreqm         `xml:"ULOCELLSECTOREQM"`
	ULZEROBUFFERZONES         []Ulzerobufferzone         `xml:"ULZeroBufferZone"`
	UPPTSINTERFCFGS           []Upptsinterfcfg           `xml:"UpPTSInterfCfg"`
	USBS                      []Usb                      `xml:"USB"`
	USERPLANEHOSTS            []Userplanehost            `xml:"USERPLANEHOST"`
	USERPLANEPEERS            []Userplanepeer            `xml:"USERPLANEPEER"`
	USERPRIORITIES            []Userpriority             `xml:"UserPriority"`
	USERQCIPRIORITIES         []Userqcipriority          `xml:"UserQciPriority"`
	USERVPFMPARAS             []Uservpfmpara             `xml:"UserVpfmPara"`
	UTRANEXTERNALCELLS        []Utranexternalcell        `xml:"UtranExternalCell"`
	UTRANNCELLS               []Utranncell               `xml:"UtranNCell"`
	UTRANNFREQS               []Utrannfreq               `xml:"UtranNFreq"`
	UTRANRANSHARES            []Utranranshare            `xml:"UtranRanShare"`
	VLANCLASSES               []Vlanclass                `xml:"VLANCLASS"`
	VLANMAPS                  []Vlanmap                  `xml:"VLANMAP"`
	VQMALGOS                  []Vqmalgo                  `xml:"VQMAlgo"`
	VRFS                      []Vrf                      `xml:"VRF"`
	WEBLMTS                   []Weblmt                   `xml:"WEBLMT"`
	WTCPPROXYALGOS            []Wtcpproxyalgo            `xml:"WtcpProxyAlgo"`
	X2S                       []X2                       `xml:"X2"`
	X2INTERFACES              []X2interface              `xml:"X2Interface"`
}
