package model

import "encoding/xml"

type Configuration struct {
	Username string
	Password string
	Hostname string
	Database string
}

type Cfgmml struct {
	XMLName        xml.Name     `xml:"BACKUPCFG"`
	SchemaLocation string       `xml:"spec,attr"`
	SPECSYNCDATA   SpecSyncData `xml:"syndata"`
}

type SpecSyncData struct {
	XMLName xml.Name `xml:"syndata"`
	CLASSES []Class  `xml:"class"`
}

type Class struct {
	XMLName                   xml.Name                   `xml:"class"`
	ALMCURCFGS                []Almcurcfg                `xml:"ALMCURCFG"`
	ALMPORTS                  []Almport                  `xml:"ALMPORT"`
	ANRS                      []Anr                      `xml:"ANR"`
	ANRMEASUREPARAMS          []Anrmeasureparam          `xml:"ANRMEASUREPARAM"`
	ANTENNAPORTS              []Antennaport              `xml:"ANTENNAPORT"`
	APPCERTS                  []Appcert                  `xml:"APPCERT"`
	APPLICATIONS              []Application              `xml:"APPLICATION"`
	ASPARAGROUPS              []Asparagroup              `xml:"ASPARAGROUP"`
	BASEBANDEQMS              []Basebandeqm              `xml:"BASEBANDEQM"`
	BBPS                      []Bbp                      `xml:"BBP"`
	BBUFANS                   []Bbufan                   `xml:"BBUFAN"`
	BCCHCFGS                  []Bcchcfg                  `xml:"BCCHCFG"`
	BLINDNCELLOPTS            []Blindncellopt            `xml:"BLINDNCELLOPT"`
	BRDRESASSIGNMENTS         []Brdresassignment         `xml:"BRDRESASSIGNMENT"`
	CABINETS                  []Cabinet                  `xml:"CABINET"`
	CAGROUPS                  []Cagroup                  `xml:"CAGROUP"`
	CAGROUPCELLS              []Cagroupcell              `xml:"CAGROUPCELL"`
	CAGROUPSCELLCFGS          []Cagroupscellcfg          `xml:"CAGROUPSCELLCFG"`
	CAMGTCFGS                 []Camgtcfg                 `xml:"CAMGTCFG"`
	CASCADEPORTS              []Cascadeport              `xml:"CASCADEPORT"`
	CELLS                     []Cell                     `xml:"Cell"`
	CELLACBARS                []Cellacbar                `xml:"CELLACBAR"`
	CELLACCESSES              []Cellaccess               `xml:"CELLACCESS"`
	CELLALGOSWITCHES          []Cellalgoswitch           `xml:"CELLALGOSWITCH"`
	CELLBACKOFFS              []Cellbackoff              `xml:"CELLBACKOFF"`
	CELLBFS                   []Cellbf                   `xml:"CELLBF"`
	CELLBFMIMOPARACFGS        []Cellbfmimoparacfg        `xml:"CELLBFMIMOPARACFG"`
	CELLCECFGS                []Cellcecfg                `xml:"CELLCECFG"`
	CELLCESCHCFGS             []Cellceschcfg             `xml:"CELLCESCHCFG"`
	CELLCHPWRCFGS             []Cellchpwrcfg             `xml:"CELLCHPWRCFG"`
	CELLCOUNTERPARAGROUPS     []Cellcounterparagroup     `xml:"CELLCOUNTERPARAGROUP"`
	CELLCQIADAPTIVECFGS       []Cellcqiadaptivecfg       `xml:"CELLCQIADAPTIVECFG"`
	CELLCQIADJALGOS           []Cellcqiadjalgo           `xml:"CELLCQIADJALGO"`
	CELLCSIRSPARACFGS         []Cellcsirsparacfg         `xml:"CELLCSIRSPARACFG"`
	CELLCSPCPARAS             []Cellcspcpara             `xml:"CELLCSPCPARA"`
	CELLDACQCFGS              []Celldacqcfg              `xml:"CELLDACQCFG"`
	CELLDLCOMPALGOS           []Celldlcompalgo           `xml:"CELLDLCOMPALGO"`
	CELLDLICICS               []Celldlicic               `xml:"CELLDLICIC"`
	CELLDLPCPDCCHES           []Celldlpcpdcch            `xml:"CELLDLPCPDCCH"`
	CELLDLPCPDSCHES           []Celldlpcpdsch            `xml:"CELLDLPCPDSCH"`
	CELLDLPCPDSCHPAS          []Celldlpcpdschpa          `xml:"CELLDLPCPDSCHPA"`
	CELLDLPCPHICHES           []Celldlpcphich            `xml:"CELLDLPCPHICH"`
	CELLDLSCHALGOS            []Celldlschalgo            `xml:"CELLDLSCHALGO"`
	CELLDRXPARAS              []Celldrxpara              `xml:"CELLDRXPARA"`
	CELLDRXSPECIALPARAS       []Celldrxspecialpara       `xml:"CELLDRXSPECIALPARA"`
	CELLDSSES                 []Celldss                  `xml:"CELLDSS"`
	CELLDYNACBARALGOPARAS     []Celldynacbaralgopara     `xml:"CELLDYNACBARALGOPARA"`
	CELLEABALGOPARAS          []Celleabalgopara          `xml:"CELLEABALGOPARA"`
	CELLEICICS                []Celleicic                `xml:"CELLEICIC"`
	CELLEMTCALGOS             []Cellemtcalgo             `xml:"CELLEMTCALGO"`
	CELLHOPARACFGS            []Cellhoparacfg            `xml:"CELLHOPARACFG"`
	CELLIDPRDUPTS             []Cellidprdupt             `xml:"CELLIDPRDUPT"`
	CELLIICSPARAS             []Celliicspara             `xml:"CELLIICSPARA"`
	CELLLOWPOWERS             []Celllowpower             `xml:"CELLLOWPOWER"`
	CELLLTEFLEXBWS            []Celllteflexbw            `xml:"CELLLTEFLEXBW"`
	CELLLTEFLEXBWITFCFGS      []Celllteflexbwitfcfg      `xml:"CELLLTEFLEXBWITFCFG"`
	CELLMBFCSES               []Cellmbfcs                `xml:"CELLMBFCS"`
	CELLMBMSCFGS              []Cellmbmscfg              `xml:"CELLMBMSCFG"`
	CELLMCPARAS               []Cellmcpara               `xml:"CELLMCPARA"`
	CELLMIMOPARACFGS          []Cellmimoparacfg          `xml:"CELLMIMOPARACFG"`
	CELLMLBS                  []Cellmlb                  `xml:"CELLMLB"`
	CELLMLBAUTOGROUPS         []Cellmlbautogroup         `xml:"CELLMLBAUTOGROUP"`
	CELLMLBHOS                []Cellmlbho                `xml:"CELLMLBHO"`
	CELLMLBUESELS             []Cellmlbuesel             `xml:"CELLMLBUESEL"`
	CELLMMALGOS               []Cellmmalgo               `xml:"CELLMMALGO"`
	CELLMROS                  []Cellmro                  `xml:"CELLMRO"`
	CELLNOACCESSALMPARAS      []Cellnoaccessalmpara      `xml:"CELLNOACCESSALMPARA"`
	CELLOPS                   []Cellop                   `xml:"CELLOP"`
	CELLPCALGOS               []Cellpcalgo               `xml:"CELLPCALGO"`
	CELLPDCCHALGOS            []Cellpdcchalgo            `xml:"CELLPDCCHALGO"`
	CELLPDCCHCECFGS           []Cellpdcchcecfg           `xml:"CELLPDCCHCECFG"`
	CELLPRBVALMLBS            []Cellprbvalmlb            `xml:"CELLPRBVALMLB"`
	CELLPUCCHALGOS            []Cellpucchalgo            `xml:"CELLPUCCHALGO"`
	CELLQCIPARAS              []Cellqcipara              `xml:"CELLQCIPARA"`
	CELLRACHALGOS             []Cellrachalgo             `xml:"CELLRACHALGO"`
	CELLRACHCECFGS            []Cellrachcecfg            `xml:"CELLRACHCECFG"`
	CELLRACTHDS               []Cellracthd               `xml:"CELLRACTHD"`
	CELLRESELS                []Cellresel                `xml:"CELLRESEL"`
	CELLRESELGERANS           []Cellreselgeran           `xml:"CELLRESELGERAN"`
	CELLRESELUTRANS           []Cellreselutran           `xml:"CELLRESELUTRAN"`
	CELLRFSHUTDOWNS           []Cellrfshutdown           `xml:"CELLRFSHUTDOWN"`
	CELLRICALGOS              []Cellricalgo              `xml:"CELLRICALGO"`
	CELLSELS                  []Cellsel                  `xml:"CELLSEL"`
	CELLSERVICEDIFFCFGS       []Cellservicediffcfg       `xml:"CELLSERVICEDIFFCFG"`
	CELLSHUTDOWNS             []Cellshutdown             `xml:"CELLSHUTDOWN"`
	CELLSIMAPS                []Cellsimap                `xml:"CELLSIMAP"`
	CELLSRLTES                []Cellsrlte                `xml:"CELLSRLTE"`
	CELLSRSADAPTIVECFGS       []Cellsrsadaptivecfg       `xml:"CELLSRSADAPTIVECFG"`
	CELLSTANDARDQCIS          []Cellstandardqci          `xml:"CELLSTANDARDQCI"`
	CELLTTIBUNDLINGALGOS      []Cellttibundlingalgo      `xml:"CELLTTIBUNDLINGALGO"`
	CELLUCIONPUSCHPARAS       []Cellucionpuschpara       `xml:"CELLUCIONPUSCHPARA"`
	CELLUEMEASCONTROLCFGS     []Celluemeascontrolcfg     `xml:"CELLUEMEASCONTROLCFG"`
	CELLULCOMPALGOS           []Cellulcompalgo           `xml:"CELLULCOMPALGO"`
	CELLULICALGOS             []Cellulicalgo             `xml:"CELLULICALGO"`
	CELLULICICS               []Cellulicic               `xml:"CELLULICIC"`
	CELLULICICMCPARAS         []Cellulicicmcpara         `xml:"CELLULICICMCPARA"`
	CELLULMIMOPARACFGS        []Cellulmimoparacfg        `xml:"CELLULMIMOPARACFG"`
	CELLULPCCOMMS             []Cellulpccomm             `xml:"CELLULPCCOMM"`
	CELLULPCDEDICS            []Cellulpcdedic            `xml:"CELLULPCDEDIC"`
	CELLULSCHALGOS            []Cellulschalgo            `xml:"CELLULSCHALGO"`
	CELLULUNIFIEDOLCS         []Cellulunifiedolc         `xml:"CELLULUNIFIEDOLC"`
	CELLUSPARACFGS            []Cellusparacfg            `xml:"CELLUSPARACFG"`
	CELLVMSES                 []Cellvms                  `xml:"CELLVMS"`
	CELLWTTXPARACFGS          []Cellwttxparacfg          `xml:"CELLWTTXPARACFG"`
	CEPUCCHCFGS               []Cepucchcfg               `xml:"CEPUCCHCFG"`
	CERACHCFGS                []Cerachcfg                `xml:"CERACHCFG"`
	CERTCFGS                  []Certcfg                  `xml:"CERTCFG"`
	CERTCHKTSKS               []Certchktsk               `xml:"CERTCHKTSK"`
	CERTDEPLOIES              []Certdeploy               `xml:"CERTDEPLOY"`
	CERTMKS                   []Certmk                   `xml:"CERTMK"`
	CERTREQS                  []Certreq                  `xml:"CERTREQ"`
	CHKS                      []Chk                      `xml:"CHK"`
	CLKDETECTS                []Clkdetect                `xml:"CLKDETECT"`
	CLZEROBUFFERZONES         []Clzerobufferzone         `xml:"CLZEROBUFFERZONE"`
	CNOPERATORS               []Cnoperator               `xml:"CNOPERATOR"`
	CNOPERATORHOCFGS          []Cnoperatorhocfg          `xml:"CNOPERATORHOCFG"`
	CNOPERATORQCIPARAS        []Cnoperatorqcipara        `xml:"CNOPERATORQCIPARA"`
	CNOPERATORSTANDARDQCIS    []Cnoperatorstandardqci    `xml:"CNOPERATORSTANDARDQCI"`
	CNOPERATORTAS             []Cnoperatorta             `xml:"CNOPERATORTA"`
	COUNTERCHECKPARAS         []Countercheckpara         `xml:"COUNTERCHECKPARA"`
	CPBEARERS                 []Cpbearer                 `xml:"CPBEARER"`
	CPRIPORTS                 []Cpriport                 `xml:"CPRIPORT"`
	CPSWITCHES                []Cpswitch                 `xml:"CPSWITCH"`
	CQIADAPTIVECFGS           []Cqiadaptivecfg           `xml:"CQIADAPTIVECFG"`
	CRLPOLICIES               []Crlpolicy                `xml:"CRLPOLICY"`
	CSFALLBACKBLINDHOCFGS     []Csfallbackblindhocfg     `xml:"CSFALLBACKBLINDHOCFG"`
	CSFALLBACKHOS             []Csfallbackho             `xml:"CSFALLBACKHO"`
	CSFALLBACKPOLICYCFGS      []Csfallbackpolicycfg      `xml:"CSFALLBACKPOLICYCFG"`
	CSPCALGOPARAS             []Cspcalgopara             `xml:"CSPCALGOPARA"`
	DEVIPS                    []Devip                    `xml:"DEVIP"`
	DHCPRELAYSWITCHES         []Dhcprelayswitch          `xml:"DHCPRELAYSWITCH"`
	DHCPSVRIPS                []Dhcpsvrip                `xml:"DHCPSVRIP"`
	DHCPSWS                   []Dhcpsw                   `xml:"DHCPSW"`
	DIFPRIS                   []Difpri                   `xml:"DIFPRI"`
	DISTBASEDHOS              []Distbasedho              `xml:"DISTBASEDHO"`
	DLFLOWCTRLPARAS           []Dlflowctrlpara           `xml:"DLFLOWCTRLPARA"`
	DRXES                     []Drx                      `xml:"DRX"`
	DRXPARAGROUPS             []Drxparagroup             `xml:"DRXPARAGROUP"`
	DSCPMAPS                  []Dscpmap                  `xml:"DSCPMAP"`
	E1T1S                     []E1t1                     `xml:"E1T1"`
	E1T1BEARS                 []E1t1bear                 `xml:"E1T1BEAR"`
	E1T1BERS                  []E1t1ber                  `xml:"E1T1BER"`
	EMCS                      []Emc                      `xml:"EMC"`
	EMUS                      []Emu                      `xml:"EMU"`
	ENBCELLOPRSVDPARAS        []Enbcelloprsvdpara        `xml:"ENBCELLOPRSVDPARA"`
	ENBCELLQCIRSVDPARAS       []Enbcellqcirsvdpara       `xml:"ENBCELLQCIRSVDPARA"`
	ENBCELLRSVDPARAS          []Enbcellrsvdpara          `xml:"ENBCELLRSVDPARA"`
	ENBCNOPQCIRSVDPARAS       []Enbcnopqcirsvdpara       `xml:"ENBCNOPQCIRSVDPARA"`
	ENBCNOPRSVDPARAS          []Enbcnoprsvdpara          `xml:"ENBCNOPRSVDPARA"`
	ENBLICENSEALMTHDS         []Enblicensealmthd         `xml:"ENBLICENSEALMTHD"`
	ENBQCIRSVDPARAS           []Enbqcirsvdpara           `xml:"ENBQCIRSVDPARA"`
	ENBRSVDPARAS              []Enbrsvdpara              `xml:"ENBRSVDPARA"`
	ENERGYCONS                []Energycon                `xml:"ENERGYCON"`
	ENODEBALGOSWITCHES        []Enodebalgoswitch         `xml:"ENODEBALGOSWITCH"`
	ENODEBALMCFGS             []Enodebalmcfg             `xml:"ENODEBALMCFG"`
	ENODEBAUTOPOWEROFFS       []Enodebautopoweroff       `xml:"ENODEBAUTOPOWEROFF"`
	ENODEBCHROUTPUTCTRLS      []Enodebchroutputctrl      `xml:"ENODEBCHROUTPUTCTRL"`
	ENODEBCIPHERCAPS          []Enodebciphercap          `xml:"ENODEBCIPHERCAP"`
	ENODEBCONNSTATETIMERS     []Enodebconnstatetimer     `xml:"ENODEBCONNSTATETIMER"`
	ENODEBFDDBBRESES          []Enodebfddbbres           `xml:"ENODEBFDDBBRES"`
	ENODEBFLOWCTRLPARAS       []Enodebflowctrlpara       `xml:"ENODEBFLOWCTRLPARA"`
	ENODEBFRAMEOFFSETS        []Enodebframeoffset        `xml:"ENODEBFRAMEOFFSET"`
	ENODEBFUNCTIONS           []Enodebfunction           `xml:"ENODEBFUNCTION"`
	ENODEBINTEGRITYCAPS       []Enodebintegritycap       `xml:"ENODEBINTEGRITYCAP"`
	ENODEBMLBS                []Enodebmlb                `xml:"ENODEBMLB"`
	ENODEBNBPARAS             []Enodebnbpara             `xml:"ENODEBNBPARA"`
	ENODEBRESMODEALGOS        []Enodebresmodealgo        `xml:"ENODEBRESMODEALGO"`
	ENODEBSHARINGMODES        []Enodebsharingmode        `xml:"ENODEBSHARINGMODE"`
	ENODEBSONDBCFGS           []Enodebsondbcfg           `xml:"ENODEBSONDBCFG"`
	ENODEBTDDBBRESES          []Enodebtddbbres           `xml:"ENODEBTDDBBRES"`
	ENODEBTGALGCFGS           []Enodebtgalgcfg           `xml:"ENODEBTGALGCFG"`
	ENODEBUSPARACFGS          []Enodebusparacfg          `xml:"ENODEBUSPARACFG"`
	EPGROUPS                  []Epgroup                  `xml:"EPGROUP"`
	EQUIPMENTS                []Equipment                `xml:"EQUIPMENT"`
	ETHPORTS                  []Ethport                  `xml:"ETHPORT"`
	EUCELLALMCFGS             []Eucellalmcfg             `xml:"EUCELLALMCFG"`
	EUCELLSECTOREQMS          []Eucellsectoreqm          `xml:"EUCELLSECTOREQM"`
	EUCOMMCELLSECTOREQMS      []Eucommcellsectoreqm      `xml:"EUCOMMCELLSECTOREQM"`
	EUCOSCHCFGS               []Eucoschcfg               `xml:"EUCOSCHCFG"`
	EUCOSCHDLCOMPCFGS         []Eucoschdlcompcfg         `xml:"EUCOSCHDLCOMPCFG"`
	EUCOSCHULICSCFGS          []Eucoschulicscfg          `xml:"EUCOSCHULICSCFG"`
	EUEPCSECS                 []Euepcsec                 `xml:"EUEPCSEC"`
	EUTRANEXTERNALCELLS       []Eutranexternalcell       `xml:"EUTRANEXTERNALCELL"`
	EUTRANINTERFREQNCELLS     []Eutraninterfreqncell     `xml:"EUTRANINTERFREQNCELL"`
	EUTRANINTERNFREQS         []Eutraninternfreq         `xml:"EUTRANINTERNFREQ"`
	EUTRANINTRAFREQNCELLS     []Eutranintrafreqncell     `xml:"EUTRANINTRAFREQNCELL"`
	EUULCOSCHCFGS             []Euulcoschcfg             `xml:"EUULCOSCHCFG"`
	EXTENDEDQCIS              []Extendedqci              `xml:"EXTENDEDQCI"`
	FDDRESMODES               []Fddresmode               `xml:"FDDRESMODE"`
	FLTCORRENABLECFGS         []Fltcorrenablecfg         `xml:"FLTCORRENABLECFG"`
	FMUS                      []Fmu                      `xml:"FMU"`
	FTPCLTS                   []Ftpclt                   `xml:"FTPCLT"`
	FTPCLTPORTS               []Ftpcltport               `xml:"FTPCLTPORT"`
	GBTSABISCPS               []Gbtsabiscp               `xml:"GBTSABISCP"`
	GBTSBBRESES               []Gbtsbbres                `xml:"GBTSBBRES"`
	GBTSENERGYMGTPARAS        []Gbtsenergymgtpara        `xml:"GBTSENERGYMGTPARA"`
	GBTSFUNCTIONS             []Gbtsfunction             `xml:"GBTSFUNCTION"`
	GBTSGLOBALPARAS           []Gbtsglobalpara           `xml:"GBTSGLOBALPARA"`
	GBTSPATHES                []Gbtspath                 `xml:"GBTSPATH"`
	GERANEXTERNALCELLS        []Geranexternalcell        `xml:"GERANEXTERNALCELL"`
	GERANINTERFCFGS           []Geraninterfcfg           `xml:"GERANINTERFCFG"`
	GERANNCELLS               []Geranncell               `xml:"GERANNCELL"`
	GERANNFREQGROUPS          []Gerannfreqgroup          `xml:"GERANNFREQGROUP"`
	GERANNFREQGROUPARFCNS     []Gerannfreqgrouparfcn     `xml:"GERANNFREQGROUPARFCN"`
	GLOBALPROCSWITCHES        []Globalprocswitch         `xml:"GLOBALPROCSWITCH"`
	GLOCELLS                  []Glocell                  `xml:"GLOCELL"`
	GLOCELLALGPARAS           []Glocellalgpara           `xml:"GLOCELLALGPARA"`
	GLOCELLENERGYMGTPARAS     []Glocellenergymgtpara     `xml:"GLOCELLENERGYMGTPARA"`
	GLOCELLOTHPARAS           []Glocellothpara           `xml:"GLOCELLOTHPARA"`
	GLOCELLRLALMPARAS         []Glocellrlalmpara         `xml:"GLOCELLRLALMPARA"`
	GLOCELLRSVDPARAS          []Glocellrsvdpara          `xml:"GLOCELLRSVDPARA"`
	GPSES                     []Gps                      `xml:"GPS"`
	GTPUS                     []Gtpu                     `xml:"GTPU"`
	GTRANSPARAS               []Gtranspara               `xml:"GTRANSPARA"`
	GTRANSPARAGWS             []Gtransparagw             `xml:"GTRANSPARAGW"`
	GTRXGROUPS                []Gtrxgroup                `xml:"GTRXGROUP"`
	GTRXGROUPSECTOREQMS       []Gtrxgroupsectoreqm       `xml:"GTRXGROUPSECTOREQM"`
	HIGHSPDADAPTIONPARAS      []Highspdadaptionpara      `xml:"HIGHSPDADAPTIONPARA"`
	HOMEASCOMMS               []Homeascomm               `xml:"HOMEASCOMM"`
	HTCDPAS                   []Htcdpa                   `xml:"HTCDPA"`
	IKECFGS                   []Ikecfg                   `xml:"IKECFG"`
	IMAGRPS                   []Imagrp                   `xml:"IMAGRP"`
	IMALNKS                   []Imalnk                   `xml:"IMALNK"`
	INGCHKTSKS                []Ingchktsk                `xml:"INGCHKTSK"`
	INTERFREQHOGROUPS         []Interfreqhogroup         `xml:"INTERFREQHOGROUP"`
	INTERRATCELLSHUTDOWNS     []Interratcellshutdown     `xml:"INTERRATCELLSHUTDOWN"`
	INTERRATHOCDMA1XRTTGROUPS []Interrathocdma1xrttgroup `xml:"INTERRATHOCDMA1XRTTGROUP"`
	INTERRATHOCDMAHRPDGROUPS  []Interrathocdmahrpdgroup  `xml:"INTERRATHOCDMAHRPDGROUP"`
	INTERRATHOCOMMS           []Interrathocomm           `xml:"INTERRATHOCOMM"`
	INTERRATHOCOMMGROUPS      []Interrathocommgroup      `xml:"INTERRATHOCOMMGROUP"`
	INTERRATHOGERANGROUPS     []Interrathogerangroup     `xml:"INTERRATHOGERANGROUP"`
	INTERRATHOUTRANGROUPS     []Interrathoutrangroup     `xml:"INTERRATHOUTRANGROUP"`
	INTERRATPOLICYCFGGROUPS   []Interratpolicycfggroup   `xml:"INTERRATPOLICYCFGGROUP"`
	INTRAFREQHOGROUPS         []Intrafreqhogroup         `xml:"INTRAFREQHOGROUP"`
	INTRARATHOCOMMS           []Intrarathocomm           `xml:"INTRARATHOCOMM"`
	IOPSCFGS                  []Iopscfg                  `xml:"IOPSCFG"`
	IPCLKLNKS                 []Ipclklnk                 `xml:"IPCLKLNK"`
	IPGUARDS                  []Ipguard                  `xml:"IPGUARD"`
	IPPATHES                  []Ippath                   `xml:"IPPATH"`
	IPPMSESSIONS              []Ippmsession              `xml:"IPPMSESSION"`
	IPRTS                     []Iprt                     `xml:"IPRT"`
	IRATNCELLCLASSMGTS        []Iratncellclassmgt        `xml:"IRATNCELLCLASSMGT"`
	IUBS                      []Iub                      `xml:"IUB"`
	IUBCPS                    []Iubcp                    `xml:"IUBCP"`
	LANSWS                    []Lansw                    `xml:"LANSW"`
	LANSWITCHPORTS            []Lanswitchport            `xml:"LANSWITCHPORT"`
	LICENSECONTROLSTRATEGIES  []Licensecontrolstrategy   `xml:"LICENSECONTROLSTRATEGY"`
	LICRATIOS                 []Licratio                 `xml:"LICRATIO"`
	LINECLKS                  []Lineclk                  `xml:"LINECLK"`
	LIOPTATOMRULES            []Lioptatomrule            `xml:"LIOPTATOMRULE"`
	LIOPTFEATURES             []Lioptfeature             `xml:"LIOPTFEATURE"`
	LIOPTFUNCTIONS            []Lioptfunction            `xml:"LIOPTFUNCTION"`
	LIOPTRULES                []Lioptrule                `xml:"LIOPTRULE"`
	LIOPTRULEMEMBERS          []Lioptrulemember          `xml:"LIOPTRULEMEMBER"`
	LLDPGLOBALS               []Lldpglobal               `xml:"LLDPGLOBAL"`
	LOCALETHPORTS             []Localethport             `xml:"LOCALETHPORT"`
	LOCALIPS                  []Localip                  `xml:"LOCALIP"`
	LOCALIP6S                 []Localip6                 `xml:"LOCALIP6"`
	LOCALWAPS                 []Localwap                 `xml:"LOCALWAP"`
	LOCATIONS                 []Location                 `xml:"LOCATION"`
	LWAMGTCFGS                []Lwamgtcfg                `xml:"LWAMGTCFG"`
	MAINSALARMBINDS           []Mainsalarmbind           `xml:"MAINSALARMBIND"`
	MANRESALMRPTS             []Manresalmrpt             `xml:"MANRESALMRPT"`
	MBMSPARAS                 []Mbmspara                 `xml:"MBMSPARA"`
	MMEFEATURECFGS            []Mmefeaturecfg            `xml:"MMEFEATURECFG"`
	MPTS                      []Mpt                      `xml:"MPT"`
	MPTRESASSIGNMENTS         []Mptresassignment         `xml:"MPTRESASSIGNMENT"`
	MROS                      []Mro                      `xml:"MRO"`
	NBCELLDLSCHCEALGOS        []Nbcelldlschcealgo        `xml:"NBCELLDLSCHCEALGO"`
	NBCELLULSCHCEALGOS        []Nbcellulschcealgo        `xml:"NBCELLULSCHCEALGO"`
	NCELLCLASSMGTS            []Ncellclassmgt            `xml:"NCELLCLASSMGT"`
	NCELLDLRSRPMEASPARAS      []Ncelldlrsrpmeaspara      `xml:"NCELLDLRSRPMEASPARA"`
	NCELLPARACFGS             []Ncellparacfg             `xml:"NCELLPARACFG"`
	NCELLSRSMEASPARAS         []Ncellsrsmeaspara         `xml:"NCELLSRSMEASPARA"`
	NES                       []Ne                       `xml:"NE"`
	NEMNTS                    []Nemnt                    `xml:"NEMNT"`
	NODES                     []Node                     `xml:"NODE"`
	NODEBALGPARAS             []Nodebalgpara             `xml:"NODEBALGPARA"`
	NODEBBBRESES              []Nodebbbres               `xml:"NODEBBBRES"`
	NODEBCHRLEVELS            []Nodebchrlevel            `xml:"NODEBCHRLEVEL"`
	NODEBCLSPATIMERS          []Nodebclspatimer          `xml:"NODEBCLSPATIMER"`
	NODEBFUNCTIONS            []Nodebfunction            `xml:"NODEBFUNCTION"`
	NODEBLICENSEALMTHDS       []Nodeblicensealmthd       `xml:"NODEBLICENSEALMTHD"`
	NODEBMULTICELLGRPS        []Nodebmulticellgrp        `xml:"NODEBMULTICELLGRP"`
	NODEBOPTDYNADJPARAS       []Nodeboptdynadjpara       `xml:"NODEBOPTDYNADJPARA"`
	NODEBPOWEROUTAGES         []Nodebpoweroutage         `xml:"NODEBPOWEROUTAGE"`
	NODEBRESALLOCRULES        []Nodebresallocrule        `xml:"NODEBRESALLOCRULE"`
	NODEBRSVDPARAS            []Nodebrsvdpara            `xml:"NODEBRSVDPARA"`
	NODEBRULEACTIONPARAS      []Nodebruleactionpara      `xml:"NODEBRULEACTIONPARA"`
	NODEBSMTHPWRS             []Nodebsmthpwr             `xml:"NODEBSMTHPWR"`
	NODEBTRFOVERLOADTHDS      []Nodebtrfoverloadthd      `xml:"NODEBTRFOVERLOADTHD"`
	NODEBUEQOSENHANCES        []Nodebueqosenhance        `xml:"NODEBUEQOSENHANCE"`
	NTPCPS                    []Ntpcp                    `xml:"NTPCP"`
	OMCHES                    []Omch                     `xml:"OMCH"`
	OPS                       []Op                       `xml:"OP"`
	OUTPORTS                  []Outport                  `xml:"OUTPORT"`
	PARAAUTOOPTCFGS           []Paraautooptcfg           `xml:"PARAAUTOOPTCFG"`
	PCCFREQCFGS               []Pccfreqcfg               `xml:"PCCFREQCFG"`
	PCCHCFGS                  []Pcchcfg                  `xml:"PCCHCFG"`
	PDCPROHCPARAS             []Pdcprohcpara             `xml:"PDCPROHCPARA"`
	PDSCHCFGS                 []Pdschcfg                 `xml:"PDSCHCFG"`
	PEERCLKS                  []Peerclk                  `xml:"PEERCLK"`
	PEUS                      []Peu                      `xml:"PEU"`
	PHICHCFGS                 []Phichcfg                 `xml:"PHICHCFG"`
	PHYPORTS                  []Phyport                  `xml:"PHYPORT"`
	PLRTHRESHOLDS             []Plrthreshold             `xml:"PLRTHRESHOLD"`
	PMTUCFGS                  []Pmtucfg                  `xml:"PMTUCFG"`
	PORTPOLICIES              []Portpolicy               `xml:"PORTPOLICY"`
	PRI2QUES                  []Pri2que                  `xml:"PRI2QUE"`
	PRIVATECABANDCOMBS        []Privatecabandcomb        `xml:"PRIVATECABANDCOMB"`
	PSUISES                   []Psuis                    `xml:"PSUIS"`
	PUCCHCFGS                 []Pucchcfg                 `xml:"PUCCHCFG"`
	PUSCHCFGS                 []Puschcfg                 `xml:"PUSCHCFG"`
	PUSCHPARAMS               []Puschparam               `xml:"PUSCHPARAM"`
	PWDPOLICIES               []Pwdpolicy                `xml:"PWDPOLICY"`
	QCIPARAS                  []Qcipara                  `xml:"QCIPARA"`
	QOEHOCOMMONCFGS           []Qoehocommoncfg           `xml:"QOEHOCOMMONCFG"`
	RACHCFGS                  []Rachcfg                  `xml:"RACHCFG"`
	RETS                      []Ret                      `xml:"RET"`
	RETDEVICEDATAS            []Retdevicedata            `xml:"RETDEVICEDATA"`
	RETPORTS                  []Retport                  `xml:"RETPORT"`
	RETSUBUNITS               []Retsubunit               `xml:"RETSUBUNIT"`
	RFUS                      []Rfu                      `xml:"RFU"`
	RLCPDCPPARAGROUPS         []Rlcpdcpparagroup         `xml:"RLCPDCPPARAGROUP"`
	RRCCONNSTATETIMERS        []Rrcconnstatetimer        `xml:"RRCCONNSTATETIMER"`
	RRUS                      []Rru                      `xml:"RRU"`
	RRUCHAINS                 []Rruchain                 `xml:"RRUCHAIN"`
	RRUJOINTCALPARACFGS       []Rrujointcalparacfg       `xml:"RRUJOINTCALPARACFG"`
	RSCGRPS                   []Rscgrp                   `xml:"RSCGRP"`
	RSCGRPALGS                []Rscgrpalg                `xml:"RSCGRPALG"`
	RXBRANCHES                []Rxbranch                 `xml:"RXBRANCH"`
	S1S                       []S1                       `xml:"S1"`
	S1INTERFACES              []S1interface              `xml:"S1INTERFACE"`
	S1REESTTIMERS             []S1reesttimer             `xml:"S1REESTTIMER"`
	SAALLNKS                  []Saallnk                  `xml:"SAALLNK"`
	SCAPPPARACFGS             []Scappparacfg             `xml:"SCAPPPARACFG"`
	SCCFREQCFGS               []Sccfreqcfg               `xml:"SCCFREQCFG"`
	SCPOLICIES                []Scpolicy                 `xml:"SCPOLICY"`
	SCSERVICEQOSES            []Scserviceqos             `xml:"SCSERVICEQOS"`
	SCTPHOSTS                 []Sctphost                 `xml:"SCTPHOST"`
	SCTPLNKS                  []Sctplnk                  `xml:"SCTPLNK"`
	SCTPPEERS                 []Sctppeer                 `xml:"SCTPPEER"`
	SCTPTEMPLATES             []Sctptemplate             `xml:"SCTPTEMPLATE"`
	SECTORS                   []Sector                   `xml:"SECTOR"`
	SECTOREQMS                []Sectoreqm                `xml:"SECTOREQM"`
	SERVICEDIFFSETTINGS       []Servicediffsetting       `xml:"SERVICEDIFFSETTING"`
	SERVICEIDENTIFYPARAS      []Serviceidentifypara      `xml:"SERVICEIDENTIFYPARA"`
	SERVICEIFDLEARFCNGRPS     []Serviceifdlearfcngrp     `xml:"SERVICEIFDLEARFCNGRP"`
	SERVICEIFHOCFGGROUPS      []Serviceifhocfggroup      `xml:"SERVICEIFHOCFGGROUP"`
	SERVICEIRHOCFGGROUPS      []Serviceirhocfggroup      `xml:"SERVICEIRHOCFGGROUP"`
	SFPS                      []Sfp                      `xml:"SFP"`
	SIMULOADS                 []Simuload                 `xml:"SIMULOAD"`
	SINGLEIPSWITCHES          []Singleipswitch           `xml:"SINGLEIPSWITCH"`
	SRBCFGS                   []Srbcfg                   `xml:"SRBCFG"`
	SRBRLCPDCPCFGS            []Srbrlcpdcpcfg            `xml:"SRBRLCPDCPCFG"`
	SRCIPRTS                  []Srciprt                  `xml:"SRCIPRT"`
	SRSADAPTIVECFGS           []Srsadaptivecfg           `xml:"SRSADAPTIVECFG"`
	SRSCFGS                   []Srscfg                   `xml:"SRSCFG"`
	SSLS                      []Ssl                      `xml:"SSL"`
	STANDARDQCIS              []Standardqci              `xml:"STANDARDQCI"`
	SUBRACKS                  []Subrack                  `xml:"SUBRACK"`
	SYNCETHES                 []Synceth                  `xml:"SYNCETH"`
	TACALGS                   []Tacalg                   `xml:"TACALG"`
	TASMS                     []Tasm                     `xml:"TASM"`
	TBDSPINFOS                []Tbdspinfo                `xml:"TBDSPINFO"`
	TBLANGNOS                 []Tblangno                 `xml:"TBLANGNO"`
	TCPACKCTRLALGOS           []Tcpackctrlalgo           `xml:"TCPACKCTRLALGO"`
	TCPACKLIMITALGS           []Tcpacklimitalg           `xml:"TCPACKLIMITALG"`
	TCPMSSCTRLS               []Tcpmssctrl               `xml:"TCPMSSCTRL"`
	TCUS                      []Tcu                      `xml:"TCU"`
	TDDFRAMEOFFSETS           []Tddframeoffset           `xml:"TDDFRAMEOFFSET"`
	TDDRESMODESWITCHES        []Tddresmodeswitch         `xml:"TDDRESMODESWITCH"`
	TIMEALIGNMENTTIMERS       []Timealignmenttimer       `xml:"TIMEALIGNMENTTIMER"`
	TIMESRCS                  []Timesrc                  `xml:"TIMESRC"`
	TIMETHRDS                 []Timethrd                 `xml:"TIMETHRD"`
	TLDRALGS                  []Tldralg                  `xml:"TLDRALG"`
	TLFRSWITCHES              []Tlfrswitch               `xml:"TLFRSWITCH"`
	TOLCALGS                  []Tolcalg                  `xml:"TOLCALG"`
	TPEALGOS                  []Tpealgo                  `xml:"TPEALGO"`
	TRPS                      []Trp                      `xml:"TRP"`
	TRUSTCERTS                []Trustcert                `xml:"TRUSTCERT"`
	TWAMPRESPONDERS           []Twampresponder           `xml:"TWAMPRESPONDER"`
	TXBRANCHES                []Txbranch                 `xml:"TXBRANCH"`
	TYPDRBBSRS                []Typdrbbsr                `xml:"TYPDRBBSR"`
	TZS                       []Tz                       `xml:"TZ"`
	UDPPINGS                  []Udpping                  `xml:"UDPPING"`
	UDTS                      []Udt                      `xml:"UDT"`
	UDTPARAGRPS               []Udtparagrp               `xml:"UDTPARAGRP"`
	UECOOPERATIONPARAS        []Uecooperationpara        `xml:"UECOOPERATIONPARA"`
	UEIUS                     []Ueiu                     `xml:"UEIU"`
	UESPECDRXPARAGROUPS       []Uespecdrxparagroup       `xml:"UESPECDRXPARAGROUP"`
	UETIMERCONSTS             []Uetimerconst             `xml:"UETIMERCONST"`
	ULCSALGOPARAS             []Ulcsalgopara             `xml:"ULCSALGOPARA"`
	ULINTERFSUPPRESSCFGS      []Ulinterfsuppresscfg      `xml:"ULINTERFSUPPRESSCFG"`
	ULOCELLS                  []Ulocell                  `xml:"ULOCELL"`
	ULOCELLALGPARAS           []Ulocellalgpara           `xml:"ULOCELLALGPARA"`
	ULOCELLMACEPARAS          []Ulocellmacepara          `xml:"ULOCELLMACEPARA"`
	ULOCELLMACHSPARAS         []Ulocellmachspara         `xml:"ULOCELLMACHSPARA"`
	ULOCELLNOACCESSPARAS      []Ulocellnoaccesspara      `xml:"ULOCELLNOACCESSPARA"`
	ULOCELLR99ALGPARAS        []Ulocellr99algpara        `xml:"ULOCELLR99ALGPARA"`
	ULOCELLRSCLMTPARAS        []Ulocellrsclmtpara        `xml:"ULOCELLRSCLMTPARA"`
	ULOCELLRSVDPARAS          []Ulocellrsvdpara          `xml:"ULOCELLRSVDPARA"`
	ULOCELLSECTOREQMS         []Ulocellsectoreqm         `xml:"ULOCELLSECTOREQM"`
	ULZEROBUFFERZONES         []Ulzerobufferzone         `xml:"ULZEROBUFFERZONE"`
	UPPTSINTERFCFGS           []Upptsinterfcfg           `xml:"UPPTSINTERFCFG"`
	USBS                      []Usb                      `xml:"USB"`
	USERPLANEHOSTS            []Userplanehost            `xml:"USERPLANEHOST"`
	USERPLANEPEERS            []Userplanepeer            `xml:"USERPLANEPEER"`
	USERPRIORITIES            []Userpriority             `xml:"USERPRIORITY"`
	USERQCIPRIORITIES         []Userqcipriority          `xml:"USERQCIPRIORITY"`
	USERVPFMPARAS             []Uservpfmpara             `xml:"USERVPFMPARA"`
	UTRANEXTERNALCELLS        []Utranexternalcell        `xml:"UTRANEXTERNALCELL"`
	UTRANNCELLS               []Utranncell               `xml:"UTRANNCELL"`
	UTRANNFREQS               []Utrannfreq               `xml:"UTRANNFREQ"`
	UTRANRANSHARES            []Utranranshare            `xml:"UTRANRANSHARE"`
	VLANCLASSES               []Vlanclass                `xml:"VLANCLASS"`
	VLANMAPS                  []Vlanmap                  `xml:"VLANMAP"`
	VQMALGOS                  []Vqmalgo                  `xml:"VQMALGO"`
	VRFS                      []Vrf                      `xml:"VRF"`
	WEBLMTS                   []Weblmt                   `xml:"WEBLMT"`
	WTCPPROXYALGOS            []Wtcpproxyalgo            `xml:"WTCPPROXYALGO"`
	X2S                       []X2                       `xml:"X2"`
	X2INTERFACES              []X2interface              `xml:"X2INTERFACE"`
}
