package model

import "encoding/xml"

type Celldlschalgo struct {
	XMLName xml.Name `xml:"CellDlschAlgo"`
	ATTRIBUTES CelldlschalgoAttributes `xml:"attributes"`
}

type CelldlschalgoAttributes struct {
	XMLName xml.Name `xml:"attributes"`
	LocalCellId string `xml:"LocalCellId"`
	DlschStrategy string `xml:"DlschStrategy"`
	FreeUserDlRbUsedRatio string `xml:"FreeUserDlRbUsedRatio"`
	MaxMimoRankPara string `xml:"MaxMimoRankPara"`
	CaSchStrategy string `xml:"CaSchStrategy"`
	NonGbrResourceRatio string `xml:"NonGbrResourceRatio"`
	DlEpfCapacityFactor string `xml:"DlEpfCapacityFactor"`
	RBPriMcsSelectRatioThd string `xml:"RBPriMcsSelectRatioThd"`
	CellEdgeUserRbAllocMode string `xml:"CellEdgeUserRbAllocMode"`
	DlIcicSchMode string `xml:"DlIcicSchMode"`
	RbgAllocStrategy string `xml:"RbgAllocStrategy"`
	MidUserMcsThreshold string `xml:"MidUserMcsThreshold"`
	DlLowLoadSdmaThdOffset string `xml:"DlLowLoadSdmaThdOffset"`
	DlHarqMaxTxNum string `xml:"DlHarqMaxTxNum"`
	NonGbrSchDelayWeight string `xml:"NonGbrSchDelayWeight"`
	RBDamageNearPointIblerTh string `xml:"RBDamageNearPointIblerTh"`
	BreathingPilotAlgoSwitch string `xml:"BreathingPilotAlgoSwitch"`
	HoStaticMcsTimer string `xml:"HoStaticMcsTimer"`
	DlRankOptimizeSwitch string `xml:"DlRankOptimizeSwitch"`
	CaSccDopMeas string `xml:"CaSccDopMeas"`
	DlSpsInterval string `xml:"DlSpsInterval"`
	RBPriMcsSelectStrategy string `xml:"RBPriMcsSelectStrategy"`
	DlRankDetectSwitch string `xml:"DlRankDetectSwitch"`
	MbsfnSfCfg string `xml:"MbsfnSfCfg"`
	TddSpecSubfSchSwitch string `xml:"TddSpecSubfSchSwitch"`
	DataThdInPdcchPdschBal string `xml:"DataThdInPdcchPdschBal"`
	UeNumThdInPdcchPdschBal string `xml:"UeNumThdInPdcchPdschBal"`
	EnbInterfRandMod string `xml:"EnbInterfRandMod"`
	TxdDci1aSwitch string `xml:"TxdDci1aSwitch"`
	DlSchAbnUeThd string `xml:"DlSchAbnUeThd"`
	RarAndPagingCR string `xml:"RarAndPagingCR"`
	CqiAdjInitialStep string `xml:"CqiAdjInitialStep"`
	CsiRsSfSchStrSwitch string `xml:"CsiRsSfSchStrSwitch"`
	SfnDlLoadPeriod string `xml:"SfnDlLoadPeriod"`
	FreqSelJudgePeriod string `xml:"FreqSelJudgePeriod"`
	DlEnhancedVoipSchSw string `xml:"DlEnhancedVoipSchSw"`
	FDUEEnhAperCQITrigPeriod string `xml:"FDUEEnhAperCQITrigPeriod"`
	SfnDlHighLoadThd string `xml:"SfnDlHighLoadThd"`
	SfnDlLowLoadThd string `xml:"SfnDlLowLoadThd"`
	DlHighLoadSdmaThdOffset string `xml:"DlHighLoadSdmaThdOffset"`
	LbtSwitch string `xml:"LbtSwitch"`
	LbtNiHighThreshold string `xml:"LbtNiHighThreshold"`
	LbtNiLowThreshold string `xml:"LbtNiLowThreshold"`
	EnAperiodicCqiTrigStrategy string `xml:"EnAperiodicCqiTrigStrategy"`
	DlCaUeCapAllocStrategy string `xml:"DlCaUeCapAllocStrategy"`
	DlCaUserSchSwitch string `xml:"DlCaUserSchSwitch"`
	Dl256QamCqiTblAdpPeriod string `xml:"Dl256QamCqiTblAdpPeriod"`
	Dl256QamCqiTblCfgStrategy string `xml:"Dl256QamCqiTblCfgStrategy"`
	BenefitMcsThreshold string `xml:"BenefitMcsThreshold"`
	DlSpsMcsDecreaseIblerThd string `xml:"DlSpsMcsDecreaseIblerThd"`
	DlAfcMaxFreq string `xml:"DlAfcMaxFreq"`
	SrsRsrpFilterCoefForDlAfc string `xml:"SrsRsrpFilterCoefForDlAfc"`
	RlcMacJointSchSw string `xml:"RlcMacJointSchSw"`
	NoSchStopACqiThd string `xml:"NoSchStopACqiThd"`
	InterPoleRruIdThld string `xml:"InterPoleRruIdThld"`
	IntraPoleRruIdDuration string `xml:"IntraPoleRruIdDuration"`
	IntraPoleRRUIdPeriod string `xml:"IntraPoleRRUIdPeriod"`
	NgbRruIdThld string `xml:"NgbRruIdThld"`
	UserSpeedDlSchPriWeight string `xml:"UserSpeedDlSchPriWeight"`
	EmimoCellRbRatio string `xml:"EmimoCellRbRatio"`
	EmimoJointSchThd string `xml:"EmimoJointSchThd"`
	EmimoIndependentSchThd string `xml:"EmimoIndependentSchThd"`
	EmimoJointIndepThdOffset string `xml:"EmimoJointIndepThdOffset"`
	StartRankDetectEffThd string `xml:"StartRankDetectEffThd"`
	StartRankDetectCntThd string `xml:"StartRankDetectCntThd"`
	RankDetectSuccessCntThd string `xml:"RankDetectSuccessCntThd"`
	RankReverseDetectCntThd string `xml:"RankReverseDetectCntThd"`
	AmbrCtrlTcycle string `xml:"AmbrCtrlTcycle"`
	CaSchWeight string `xml:"CaSchWeight"`
	PosNegFoRatioThd string `xml:"PosNegFoRatioThd"`
	UserFoThdForDlAfc string `xml:"UserFoThdForDlAfc"`
	ZoneUserNumRatioThd string `xml:"ZoneUserNumRatioThd"`
	CrsFullBwPostODTtiNum string `xml:"CrsFullBwPostODTtiNum"`
	CrsFullBwPreODTtiNum string `xml:"CrsFullBwPreODTtiNum"`
	CrsFullBwPreSibPagingTtiNum string `xml:"CrsFullBwPreSibPagingTtiNum"`
	UeAttJudgePeriod string `xml:"UeAttJudgePeriod"`
	UeAttJudgeRsrpHyst string `xml:"UeAttJudgeRsrpHyst"`
	BPUeOdAlignThd string `xml:"BPUeOdAlignThd"`
	PrbEnableThldVideoResCtrl string `xml:"PrbEnableThldVideoResCtrl"`
	IblerPdcchSinrOffset string `xml:"IblerPdcchSinrOffset"`
	FSUEAperCQITrigPeriod string `xml:"FSUEAperCQITrigPeriod"`
	FSUESbCQIValidityPeriod string `xml:"FSUESbCQIValidityPeriod"`
	InterfRandPciOffset string `xml:"InterfRandPciOffset"`
	PilotOffStrategy string `xml:"PilotOffStrategy"`
	CrsCompensatePeriod string `xml:"CrsCompensatePeriod"`
	DlFirstHarqTxTbsIncNum string `xml:"DlFirstHarqTxTbsIncNum"`
	NbDlHarqMaxTxCount string `xml:"NbDlHarqMaxTxCount"`
	CongestMaxVideoRate string `xml:"CongestMaxVideoRate"`
	UserEnableThldVideoResCtrl string `xml:"UserEnableThldVideoResCtrl"`
	PilotOffDrxParaGroupId string `xml:"PilotOffDrxParaGroupId"`
	MccsCqiPeriodThld string `xml:"MccsCqiPeriodThld"`
	MccsPrbRateThld string `xml:"MccsPrbRateThld"`
	MultiCarrierCoSchAlgoSw string `xml:"MultiCarrierCoSchAlgoSw"`
	OverlapRsrpIsolationThd string `xml:"OverlapRsrpIsolationThd"`
	CbtcDlSchedulingMcsUpLimit string `xml:"CbtcDlSchedulingMcsUpLimit"`
	DlEnhMuCellRbRatioThld string `xml:"DlEnhMuCellRbRatioThld"`
	DlEnhMuCellAvgCQIThd string `xml:"DlEnhMuCellAvgCQIThd"`
	DlEnhMuPrbPairRatioThld string `xml:"DlEnhMuPrbPairRatioThld"`
	DlEnhMuOnOffTimer string `xml:"DlEnhMuOnOffTimer"`
	HighIblerTargetTbsIdxThld string `xml:"HighIblerTargetTbsIdxThld"`
	LowIblerTargetTbsIdxThld string `xml:"LowIblerTargetTbsIdxThld"`
	DlCandPairUeCntThld string `xml:"DlCandPairUeCntThld"`
	PdschMaxCodeRate string `xml:"PdschMaxCodeRate"`
	IndependentBeamPmiThld string `xml:"IndependentBeamPmiThld"`
}

