package model

import "encoding/xml"

type Glocellothpara struct {
	XMLName xml.Name `xml:"GLOCELLOTHPARA"`
	ATTRIBUTES GlocellothparaAttributes `xml:"attributes"`
}

type GlocellothparaAttributes struct {
	XMLName xml.Name `xml:"attributes"`
	GLOCELLID string `xml:"GLOCELLID"`
	MULTRXBRDSTABMONITUNNSW string `xml:"MULTRXBRDSTABMONITUNNSW"`
	MULTRXBRDUNSTABMONITUNNSW string `xml:"MULTRXBRDUNSTABMONITUNNSW"`
	IMMOCCUPYPCHOPTSW string `xml:"IMMOCCUPYPCHOPTSW"`
	PCHFORBIDRPTLOADSW string `xml:"PCHFORBIDRPTLOADSW"`
	PTCCHPOWEROPTSW string `xml:"PTCCHPOWEROPTSW"`
	FIRSTMROPTSW string `xml:"FIRSTMROPTSW"`
	SPEECHDELAYOPTSW string `xml:"SPEECHDELAYOPTSW"`
	SPEECHBADFRAMEOPTSW string `xml:"SPEECHBADFRAMEOPTSW"`
	PAGINGOVLDPROCOPTSW string `xml:"PAGINGOVLDPROCOPTSW"`
	RFMODULESTDETECTSW string `xml:"RFMODULESTDETECTSW"`
	NOTRAFFICSELFHEALSW string `xml:"NOTRAFFICSELFHEALSW"`
}

