package model

import "encoding/xml"

type Nodebrsvdpara struct {
	XMLName xml.Name `xml:"NODEBRSVDPARA"`
	ATTRIBUTES NodebrsvdparaAttributes `xml:"attributes"`
}

type NodebrsvdparaAttributes struct {
	XMLName xml.Name `xml:"attributes"`
	NODEBRSVDPARA1 string `xml:"NODEBRSVDPARA1"`
	NODEBRSVDPARA2 string `xml:"NODEBRSVDPARA2"`
	NODEBRSVDPARA3 string `xml:"NODEBRSVDPARA3"`
	NODEBRSVDPARA4 string `xml:"NODEBRSVDPARA4"`
	NODEBRSVDPARA5 string `xml:"NODEBRSVDPARA5"`
	NODEBRSVDPARA6 string `xml:"NODEBRSVDPARA6"`
	NODEBRSVDPARA7 string `xml:"NODEBRSVDPARA7"`
	NODEBRSVDPARA8 string `xml:"NODEBRSVDPARA8"`
	NODEBRSVDPARA9 string `xml:"NODEBRSVDPARA9"`
	NODEBRSVDPARA10 string `xml:"NODEBRSVDPARA10"`
	NODEBRSVDPARA11 string `xml:"NODEBRSVDPARA11"`
	NODEBRSVDPARA12 string `xml:"NODEBRSVDPARA12"`
	OBJID string `xml:"OBJID"`
	NODEBRSVDPARA13 string `xml:"NODEBRSVDPARA13"`
	NODEBRSVDPARA14 string `xml:"NODEBRSVDPARA14"`
	NODEBRSVDPARA15 string `xml:"NODEBRSVDPARA15"`
	NODEBRSVDPARA16 string `xml:"NODEBRSVDPARA16"`
	NODEBRSVDPARA17 string `xml:"NODEBRSVDPARA17"`
	NODEBRSVDPARA18 string `xml:"NODEBRSVDPARA18"`
	NODEBRSVDPARA19 string `xml:"NODEBRSVDPARA19"`
	NODEBRSVDPARA20 string `xml:"NODEBRSVDPARA20"`
	NODEBRSVDPARA21 string `xml:"NODEBRSVDPARA21"`
	NODEBRSVDPARA22 string `xml:"NODEBRSVDPARA22"`
	NODEBRSVDPARA23 string `xml:"NODEBRSVDPARA23"`
	NODEBRSVDPARA24 string `xml:"NODEBRSVDPARA24"`
	NODEBRSVDPARA25 string `xml:"NODEBRSVDPARA25"`
	NODEBRSVDPARA26 string `xml:"NODEBRSVDPARA26"`
	NODEBRSVDPARA27 string `xml:"NODEBRSVDPARA27"`
	NODEBRSVDPARA28 string `xml:"NODEBRSVDPARA28"`
	NODEBRSVDPARA29 string `xml:"NODEBRSVDPARA29"`
	NODEBRSVDPARA30 string `xml:"NODEBRSVDPARA30"`
	NODEBRSVDPARA31 string `xml:"NODEBRSVDPARA31"`
	NODEBRSVDPARA32 string `xml:"NODEBRSVDPARA32"`
}

