package model

import "encoding/xml"

type Nodebalgpara struct {
	XMLName xml.Name `xml:"NODEBALGPARA"`
	ATTRIBUTES NodebalgparaAttributes `xml:"attributes"`
}

type NodebalgparaAttributes struct {
	XMLName xml.Name `xml:"attributes"`
	OBJID string `xml:"OBJID"`
	CERSVFOR2MSUSER string `xml:"CERSVFOR2MSUSER"`
	CCPICPHASESWCTRL string `xml:"CCPICPHASESWCTRL"`
	HSDPASCHPOOLSW string `xml:"HSDPASCHPOOLSW"`
	PWRCHKSW string `xml:"PWRCHKSW"`
	CCPICPH2SIRTARMODSW string `xml:"CCPICPH2SIRTARMODSW"`
	ADPRETRANSSW string `xml:"ADPRETRANSSW"`
	FRTRJT string `xml:"FRTRJT"`
	INTERBOARDICSW string `xml:"INTERBOARDICSW"`
	SLEEPINGCELLDETECTSW string `xml:"SLEEPINGCELLDETECTSW"`
	UTRPCEXTCNBAPCAP string `xml:"UTRPCEXTCNBAPCAP"`
	RTWPSCALEPRECISIONOPT string `xml:"RTWPSCALEPRECISIONOPT"`
	CEDETECTPERIODLEVEL string `xml:"CEDETECTPERIODLEVEL"`
	ULRESWORKMODE string `xml:"ULRESWORKMODE"`
	CEIMPROVEMENT2MSSW string `xml:"CEIMPROVEMENT2MSSW"`
	INITSINGLEHARQSW string `xml:"INITSINGLEHARQSW"`
	ULHITHPMACESW string `xml:"ULHITHPMACESW"`
	ULINNERPCABNRISECTRLSW string `xml:"ULINNERPCABNRISECTRLSW"`
	KPIFAULTDETECTSW string `xml:"KPIFAULTDETECTSW"`
	KPIFAULTAUTORCVRMTHD string `xml:"KPIFAULTAUTORCVRMTHD"`
	FIXEDCERSVFOR2MS string `xml:"FIXEDCERSVFOR2MS"`
	DLTXPWRMEASPERIOD string `xml:"DLTXPWRMEASPERIOD"`
	PWRPREDICTSWFORCAC string `xml:"PWRPREDICTSWFORCAC"`
	DLFPWINADJSW string `xml:"DLFPWINADJSW"`
	HSPAMCINTERBRDSCHSW string `xml:"HSPAMCINTERBRDSCHSW"`
	R99FAULTTHD string `xml:"R99FAULTTHD"`
	UPAFAULTTHD string `xml:"UPAFAULTTHD"`
	PROCUNITFAULTTHD string `xml:"PROCUNITFAULTTHD"`
	PROTECTIONTHD string `xml:"PROTECTIONTHD"`
	PROCUNITFAULTCLEARTHD string `xml:"PROCUNITFAULTCLEARTHD"`
	ALMOCCURPRD string `xml:"ALMOCCURPRD"`
	ALMCLEARPRD string `xml:"ALMCLEARPRD"`
	PDMEASMSW string `xml:"PDMEASMSW"`
	ULCCHOLPCMINSIRTARGET string `xml:"ULCCHOLPCMINSIRTARGET"`
	HSUPASCHPOOLSW string `xml:"HSUPASCHPOOLSW"`
	ULCOVEXPCFGMOD string `xml:"ULCOVEXPCFGMOD"`
	PWRCFGPROTECT string `xml:"PWRCFGPROTECT"`
	UPCEIMPROVEFORAMRWBSW string `xml:"UPCEIMPROVEFORAMRWBSW"`
	NBISADAPTIVESW string `xml:"NBISADAPTIVESW"`
	UX2SONSETUPSW string `xml:"UX2SONSETUPSW"`
	SLEEPINGCELLALARMSW string `xml:"SLEEPINGCELLALARMSW"`
	SLEEPINGCELLDETECTOPTION string `xml:"SLEEPINGCELLDETECTOPTION"`
	RFFAULTCTRSW string `xml:"RFFAULTCTRSW"`
	CPCFDPCHDTXSW string `xml:"CPCFDPCHDTXSW"`
	IUBCONGESTKPIIMPROVESW string `xml:"IUBCONGESTKPIIMPROVESW"`
	HSDPASERCELLCHOPTSW string `xml:"HSDPASERCELLCHOPTSW"`
	CELLRTWPEXCESSALMSW string `xml:"CELLRTWPEXCESSALMSW"`
	CELLRTWPEXCESSALMTHD string `xml:"CELLRTWPEXCESSALMTHD"`
	VAMPWRSAVSW string `xml:"VAMPWRSAVSW"`
	VAMPWRSAVSTARTTIME string `xml:"VAMPWRSAVSTARTTIME"`
	VAMPWRSAVSTOPTIME string `xml:"VAMPWRSAVSTOPTIME"`
	VAMPWRSAVTXPWRLOWTHD string `xml:"VAMPWRSAVTXPWRLOWTHD"`
	VAMPWRSAVTXPWRHIGHTHD string `xml:"VAMPWRSAVTXPWRHIGHTHD"`
	DLAUTORESHUFFLESW string `xml:"DLAUTORESHUFFLESW"`
	ADPETADJFLAG string `xml:"ADPETADJFLAG"`
	AMRTRANSBWCOMP string `xml:"AMRTRANSBWCOMP"`
	SFSSWITCH string `xml:"SFSSWITCH"`
	KPIFAULTDETECT string `xml:"KPIFAULTDETECT"`
	RRUINTELDORFEQBAND string `xml:"RRUINTELDORFEQBAND"`
	OPERATORSHARECEMODE string `xml:"OPERATORSHARECEMODE"`
	OPERATORINDEXSELECTION string `xml:"OPERATORINDEXSELECTION"`
	NBISRESELPERIOD string `xml:"NBISRESELPERIOD"`
	RTWPIMBALANCEALMTHD string `xml:"RTWPIMBALANCEALMTHD"`
	NBISINIACTTHD string `xml:"NBISINIACTTHD"`
}

