package model

import "encoding/xml"

type Ulocellmachspara struct {
	XMLName xml.Name `xml:"ULOCELLMACHSPARA"`
	ATTRIBUTES UlocellmachsparaAttributes `xml:"attributes"`
}

type UlocellmachsparaAttributes struct {
	XMLName xml.Name `xml:"attributes"`
	ULOCELLID string `xml:"ULOCELLID"`
	RSCALLOCM string `xml:"RSCALLOCM"`
	SM string `xml:"SM"`
	PWRMGN string `xml:"PWRMGN"`
	HSSCCHPWRCMINDCH string `xml:"HSSCCHPWRCMINDCH"`
	SCCHPWR string `xml:"SCCHPWR"`
	HSSCCHFERTRGTINDCH string `xml:"HSSCCHFERTRGTINDCH"`
	RSCLMSW string `xml:"RSCLMSW"`
	DYNCODESW string `xml:"DYNCODESW"`
	CME16QAMSW string `xml:"CME16QAMSW"`
	MXPWRPHUSR string `xml:"MXPWRPHUSR"`
	CQIFA string `xml:"CQIFA"`
	MAXEFACHHARQRT string `xml:"MAXEFACHHARQRT"`
	MAXNONCONVERHARQRT string `xml:"MAXNONCONVERHARQRT"`
	HSSCCHPWRCMINEFACH string `xml:"HSSCCHPWRCMINEFACH"`
	CQIADJALGOFCON string `xml:"CQIADJALGOFCON"`
	CQIADJALGOFNONCON string `xml:"CQIADJALGOFNONCON"`
	RBLERTARGET string `xml:"RBLERTARGET"`
	IBLERTARGET string `xml:"IBLERTARGET"`
	SECCELLACTDEASW string `xml:"SECCELLACTDEASW"`
	IICSW string `xml:"IICSW"`
	DTXALGOSW string `xml:"DTXALGOSW"`
	MIMOPRIMESW string `xml:"MIMOPRIMESW"`
	LOCWEIGHT string `xml:"LOCWEIGHT"`
	EXTRAPOWER string `xml:"EXTRAPOWER"`
	MAXEFACHHSHARQRT string `xml:"MAXEFACHHSHARQRT"`
	BURSTBLEROPTSW string `xml:"BURSTBLEROPTSW"`
	DLBESCHWHENULURLBSW string `xml:"DLBESCHWHENULURLBSW"`
	EXTRAPOWERFORSRB string `xml:"EXTRAPOWERFORSRB"`
	CODEOPTSW string `xml:"CODEOPTSW"`
	PREALLOCBWOPTISW string `xml:"PREALLOCBWOPTISW"`
	SFDCMACEHSDSCTMR string `xml:"SFDCMACEHSDSCTMR"`
	DF3CMACEHSDSCTMR string `xml:"DF3CMACEHSDSCTMR"`
	HSDPAL2OPTSW string `xml:"HSDPAL2OPTSW"`
	PWRMGNDELTAFORPT string `xml:"PWRMGNDELTAFORPT"`
	VIDEOCQITHD string `xml:"VIDEOCQITHD"`
	HSDPAFULLBUFDATATHD string `xml:"HSDPAFULLBUFDATATHD"`
	HSDPAFULLBUFTHROUTHD string `xml:"HSDPAFULLBUFTHROUTHD"`
	HSSCCHCQIPWRINDCHOPTSW string `xml:"HSSCCHCQIPWRINDCHOPTSW"`
	MAXEXTRAPWRFORHSSCCHINDCH string `xml:"MAXEXTRAPWRFORHSSCCHINDCH"`
	SERVICECQITHD string `xml:"SERVICECQITHD"`
	EFACHDTCHRSCALLOCMODE string `xml:"EFACHDTCHRSCALLOCMODE"`
	CQIADJBYIBLERADJSW string `xml:"CQIADJBYIBLERADJSW"`
	CQIADJBYDYNBLERADJSW string `xml:"CQIADJBYDYNBLERADJSW"`
	ACTSECCELLTHPTHD string `xml:"ACTSECCELLTHPTHD"`
	DEASECCELLTHPTHD string `xml:"DEASECCELLTHPTHD"`
	ACTSECCELLDATABUFTHD string `xml:"ACTSECCELLDATABUFTHD"`
	DEASECCELLDATABUFTHD string `xml:"DEASECCELLDATABUFTHD"`
	INDEPTCARSCHSW string `xml:"INDEPTCARSCHSW"`
	BUFFERSMSW string `xml:"BUFFERSMSW"`
	DYNCODEOPTSW string `xml:"DYNCODEOPTSW"`
	HARQRTSCHOPTSW string `xml:"HARQRTSCHOPTSW"`
	MCDELTACQITHD string `xml:"MCDELTACQITHD"`
}

