package model

import "encoding/xml"

type Ulocellmacepara struct {
	XMLName xml.Name `xml:"ULOCELLMACEPARA"`
	ATTRIBUTES UlocellmaceparaAttributes `xml:"attributes"`
}

type UlocellmaceparaAttributes struct {
	XMLName xml.Name `xml:"attributes"`
	ULOCELLID string `xml:"ULOCELLID"`
	SCHEDULEPARA string `xml:"SCHEDULEPARA"`
	HSUPAOLSCHSW string `xml:"HSUPAOLSCHSW"`
	MAXDELTAOFTARGETROT string `xml:"MAXDELTAOFTARGETROT"`
	EAGCHPCPARA string `xml:"EAGCHPCPARA"`
	EAGCHPCMOD string `xml:"EAGCHPCMOD"`
	EAGCHPWROFFSET string `xml:"EAGCHPWROFFSET"`
	EAGCHPOWER string `xml:"EAGCHPOWER"`
	MAXAGCHPOWER string `xml:"MAXAGCHPOWER"`
	MINAGCHPOWER string `xml:"MINAGCHPOWER"`
	SERGCHPCPARA string `xml:"SERGCHPCPARA"`
	SERGCHPCMOD string `xml:"SERGCHPCMOD"`
	SERGCHPWROFFSET string `xml:"SERGCHPWROFFSET"`
	SERGCHPOWER string `xml:"SERGCHPOWER"`
	NSERGCHPCPARA string `xml:"NSERGCHPCPARA"`
	NSERGCHPCMOD string `xml:"NSERGCHPCMOD"`
	NSERGCHPWROFFSET string `xml:"NSERGCHPWROFFSET"`
	NSERGCHPOWER string `xml:"NSERGCHPOWER"`
	SEHICHPCPARA string `xml:"SEHICHPCPARA"`
	SEHICHPWROFFSET string `xml:"SEHICHPWROFFSET"`
	SEHICHPOWER string `xml:"SEHICHPOWER"`
	SRLEHICHPWROFFSET string `xml:"SRLEHICHPWROFFSET"`
	SINGLERLEHICHPOWER string `xml:"SINGLERLEHICHPOWER"`
	NSEHICHPCPARA string `xml:"NSEHICHPCPARA"`
	NSEHICHPWROFFSET string `xml:"NSEHICHPWROFFSET"`
	NSEHICHPOWER string `xml:"NSEHICHPOWER"`
	OUTERSYSINTERSCHSW string `xml:"OUTERSYSINTERSCHSW"`
	OWNCELLULLOADRATIO string `xml:"OWNCELLULLOADRATIO"`
	RTWPMEAOPTIMSW string `xml:"RTWPMEAOPTIMSW"`
	LOADTHRESH4MINULCOV string `xml:"LOADTHRESH4MINULCOV"`
	HSUPATDSCHSW string `xml:"HSUPATDSCHSW"`
	HSUPATDALIGNUENUM string `xml:"HSUPATDALIGNUENUM"`
	HSUPATDSCHENSW string `xml:"HSUPATDSCHENSW"`
	RTWPSINGLEHARQSCHSW string `xml:"RTWPSINGLEHARQSCHSW"`
	ULSECCELLACTOPTSW string `xml:"ULSECCELLACTOPTSW"`
	ULSECCELLDEACTCOVTHR string `xml:"ULSECCELLDEACTCOVTHR"`
	HSUPATOTALTHRGUARANTEESW string `xml:"HSUPATOTALTHRGUARANTEESW"`
	HSUPATOTALTHRTHD string `xml:"HSUPATOTALTHRTHD"`
}

