package model

import "encoding/xml"

type Ulocellrsvdpara struct {
	XMLName xml.Name `xml:"ULOCELLRSVDPARA"`
	ATTRIBUTES UlocellrsvdparaAttributes `xml:"attributes"`
}

type UlocellrsvdparaAttributes struct {
	XMLName xml.Name `xml:"attributes"`
	ULOCELLID string `xml:"ULOCELLID"`
	ULOCELLRSVDPARA1 string `xml:"ULOCELLRSVDPARA1"`
	ULOCELLRSVDPARA2 string `xml:"ULOCELLRSVDPARA2"`
	ULOCELLRSVDPARA3 string `xml:"ULOCELLRSVDPARA3"`
	ULOCELLRSVDPARA4 string `xml:"ULOCELLRSVDPARA4"`
	ULOCELLRSVDPARA5 string `xml:"ULOCELLRSVDPARA5"`
	ULOCELLRSVDPARA6 string `xml:"ULOCELLRSVDPARA6"`
	ULOCELLRSVDPARA7 string `xml:"ULOCELLRSVDPARA7"`
	ULOCELLRSVDPARA8 string `xml:"ULOCELLRSVDPARA8"`
	ULOCELLRSVDPARA9 string `xml:"ULOCELLRSVDPARA9"`
	ULOCELLRSVDPARA10 string `xml:"ULOCELLRSVDPARA10"`
	ULOCELLRSVDPARA11 string `xml:"ULOCELLRSVDPARA11"`
	ULOCELLRSVDPARA12 string `xml:"ULOCELLRSVDPARA12"`
	ULOCELLRSVDPARA13 string `xml:"ULOCELLRSVDPARA13"`
	ULOCELLRSVDPARA14 string `xml:"ULOCELLRSVDPARA14"`
	ULOCELLRSVDPARA15 string `xml:"ULOCELLRSVDPARA15"`
	ULOCELLRSVDPARA16 string `xml:"ULOCELLRSVDPARA16"`
	ULOCELLRSVDPARA17 string `xml:"ULOCELLRSVDPARA17"`
	ULOCELLRSVDPARA18 string `xml:"ULOCELLRSVDPARA18"`
	ULOCELLRSVDPARA19 string `xml:"ULOCELLRSVDPARA19"`
	ULOCELLRSVDPARA20 string `xml:"ULOCELLRSVDPARA20"`
	ULOCELLRSVDPARA21 string `xml:"ULOCELLRSVDPARA21"`
	ULOCELLRSVDPARA22 string `xml:"ULOCELLRSVDPARA22"`
	ULOCELLRSVDPARA23 string `xml:"ULOCELLRSVDPARA23"`
	ULOCELLRSVDPARA24 string `xml:"ULOCELLRSVDPARA24"`
	ULOCELLRSVDPARA25 string `xml:"ULOCELLRSVDPARA25"`
	ULOCELLRSVDPARA26 string `xml:"ULOCELLRSVDPARA26"`
	ULOCELLRSVDPARA27 string `xml:"ULOCELLRSVDPARA27"`
	ULOCELLRSVDPARA28 string `xml:"ULOCELLRSVDPARA28"`
	ULOCELLRSVDPARA29 string `xml:"ULOCELLRSVDPARA29"`
	ULOCELLRSVDPARA30 string `xml:"ULOCELLRSVDPARA30"`
	ULOCELLRSVDPARA31 string `xml:"ULOCELLRSVDPARA31"`
	ULOCELLRSVDPARA32 string `xml:"ULOCELLRSVDPARA32"`
}

